# Lotka-Volterra competition

In ecology the there is a "rule" called the "competitive exclusion principle" which states that two species cannot coexist unless their niches are sufficiently different. 

How different do their niches need to be for coexistence? The general idea is that coexistence can occur if each species limits its own population growth rate more than it limits the growth rate of the other species. 

If there the niches overlap too much, one species will competitively exclude the other (i.e. forces the other to extinction).

In this class you will be working from a PDF available [here](https://www.dropbox.com/s/oukr39oq0rsn8il/9.%20Interspecific%20Competition%20and%20Competitive%20Exclusion.pdf?dl=1) to explore this idea.

This PDF walks you through the creation of an Excel spreadsheet exploring interspecific competition and competitive exclusion using the Lotka-Volterra model. 

Your task:

* Create the Excel spreadsheet by following the instructions in the PDF
* Use the Lotka-Volterra model you have created to answer the questions at the end of the PDF.

These questions are:

1.  What parameter values will cause species 1 to exclude species 2 from the habi- tat? What do these values mean in ecological terms?
2. What parameter values will reverse this outcome? What do these values mean in ecological terms?
3. What parameter values will allow the two species to coexist indefinitely and stably? What do these values mean in ecological terms?
4. Are there parameter values under which the outcome depends on initial population sizes or rates of population growth? What do these values mean in ecological terms?

