# Deeper into logistic growth

## Background

The purpose of this exercise is (i) to look at the relationships between the exponential (or geometric) growth model and the logistic growth model and (ii) to emphasise different ways of looking at the models.

```{block, type="do-something"}
Learning outcomes: 

- Increased competence in using Excel formulae for mathematical modeling.
- Understanding the relationship between exponential and logistic growth models.
- Understanding how models can be modified to explore different phenomena.
- Understanding how and why model outputs can be explored (visualised) from different perspectives.
- Competence in using mathematical models in Excel to strengthen own understanding of biological processes.

```

## Your task

### Relationship between Geometric and Logistic models

Consider the logistic growth model (Eqn. 5.2 in Neal):

$\frac{\delta N}{\delta t}=r_m N\left(1-\frac{N}{K}\right)$

This model includes carrying capacity (K) to account for the fact that, in most situations, the environment imposes a limit on the number of individuals that can be supported. What happens if we remove that limit? We can do that mathematically by setting K to be infinity.

$\frac{\delta N}{\delta t}=r_m N\left(1-\frac{N}{\infty}\right)$

What do we get if we divide a number by infinity? ... zero.

So we get: 

$\frac{\delta N}{\delta t}=r_m N\left(1-0\right)$, or, 

$\frac{\delta N}{\delta t}=r_m N$, which is the ordinary geometric growth equation (Eqn. 4.6 in Neal)!


The take-home message here is that these key equations are closely related, and you can go from one to the other with some simple, logical steps.




### Different views of the basic logistic growth model

Download the Excel file [`Deeper Into Logistic Growth.xlsx`](https://www.dropbox.com/s/4xq399z7skl1akv/Deeper%20into%20Logistic%20Growth.xlsx?dl=1).


Take a look at the `BasicLogistic` Excel worksheet/ark, and answer the questions below.

Focus first on **Figure 1**.

Enter different values for $r_m$, e.g. 0.8, 1.2, 1.8, 2.4, 2.7…

Can you describe the dynamics of the population time series in Figure 1 using some of the following vocabulary: Oscillation, damped oscillation, stable cycle, 2-point cycle, chaotic, unpredictable, predictable?

Now focus on **Figure 2**.

This figure shows the per capita population growth rate as a function of population size at time $t$. Note where the line intercepts the x- and y-axes. 

What do you notice about these values? Hint: what are the values you have set for $r_m$ and $K$? Try varying those values.

On paper, make a sketch of a graph for per capita population growth rate as a function of population size at time t for a logistic model with $r_m$ = 1.5 and $K$ = 250, indicating the values of the intercepts. Check your sketch by entering those values into the Excel model.

This relates to Eqn. 5.1 in Neal: $r = r_m(1-N/K)$. 

Based on what you know about what happens to the population dynamics for different values of $r_m$ and what you have just seen in Figure 2, you should now be able to sketch fairly accurate cartoon graphs if you are given values for $r_m$ and $K$! 

*Without using Excel*, draw a population time series, and a graph of per capita growth rate vs. N for when initial population size is 10, $r_m$ is 1.9 and $K$ is 500. Check your graph using Excel.  

Focus now on **Figure 3**.

Population growth rate is $dN/dt$ - the rate of change in $N$ ($dN$, change in population size) per unit time ($dt$). You should now explore how *Figure 3* relates to the values used in the equation by changing the $r_m$ and $K$ values and looking at *Figure 3*. 

Can you see how *Figures 1*, *2* and *3* are connected?

At what population sizes is the population growth rate 0 ($dN/dt$)?
What is the population size at which the population growth is rate maximized? 

Now lets look back on **Exponential growth**.

How do the relationships in Figures 1, 2 and 3, differ from the equivalent figures for logistic growth. Try to draw graphs of Figures 1, 2 and 3 for the exponential growth model.

*	Fig 1. Population size ($N$) through time ($t$).
*	Fig 2. Per capita growth rate ($\frac{1}{N} \frac{dN}{dt}$) vs. population size ($N$)
*	Fig 3. Population growth rate ($\frac{dN}{dt}$) vs. population size ($N$) (see figure 2.4 in Gotelli)


### Adding a time lag

This relates to *Equation 2.3* in Gotelli (and pages 32-35).

$\frac{d N}{d t}=r N\left(1-\frac{N_{t-\tau}}{K}\right)$

Look at the Excel Worksheet/Ark called `TimeLag`.

Adding a time lag to logistic model can complicate the dynamics (by introducing cycling). The 3rd Excel tab has an exercise showing that if you add in a time lag to the logistic function it modifies the dynamics. The purpose of this Excel sheet is to allow you to prove this to yourself!

You will need to carefully modify the Excel formula so that instead of referring back to the population size at $N_{t-1}$, it refers back to $N_{t-1}$ etc. Remember to drag the formula down to all the other years (or use the shortcut I will show you).

Start with a small $r_m$ that gives a smooth convergence to K with an ordinary logistic model. Add in a 1-year time lag and show that this generates cyclic dynamics. This shows that this simple “quirk of life history” (a time lag) can generate cycling, even if the population growth rate is low.
 

