# Solutions and "take-home" messages

In this section you will find the solutions and/or main take home messages of the practical exercises used in this course.


## Solutions: The legend of Ambalapuzha

You can find the completed Excel file [here](https://www.dropbox.com/s/ybe5qhmfltuhoyv/RiceOnAChessboard_completed.xlsx?dl=1).

Take home messages:

* Exponential/geometric growth is extremely powerful and can very quickly lead to very large numbers.

## Solutions: Geometric growth

You can find the completed Excel file [here](https://www.dropbox.com/s/sfxu1lbrxyqt462/GeometricGrowth%20-%20complete.xlsx?dl=1). 

Take home messages:

* The rate of exponential/geometric growth depends on the population growth rate.
* Lambda ($\lambda$) values $<1$ lead to a exponential *decrease*, while values $>1$ lead to exponential growth. A $\lambda$ of 1 indicates no change.
* Exponential growth is unlimited. This is unrealistic because very soon competition (what Darwin called "The struggle for existence") will soon take effect as the population runs out of space or resources. Nevertheless, the model is useful and realistic for some limited situations (e.g. early population growth for new invaders)
* Growth trajectories can be plotted on the *natural scale* or on a *log scale*. Exponential growth (or decline) plotted on a log scale is a straight line. This could be useful to infer biological processes (or the lack of them). For example, exponential growth in population size indicates that there are no forces currently limiting the population (e.g. predators/competition/management actions).
* The slope of the population growth on the natural log scale can tell you what $\lambda$ is. The "opposite" of *ln* is *exp*, so you can ask Excel to `=EXP(slope).


## Solutions: Stochastic population growth

You can find the completed Excel file [here](https://www.dropbox.com/s/baao06vi0c0quns/StochasticPopulationGrowth-complete.xlsx?dl=1).

Take home messages:

* Population growth rates are unlikely to be constant through time.
* Environmental stochasticity will cause changes through time in vital rates (birth/death) which will influence $\lambda$ (and $r_m$).
* We can model environmental stochasticity using a distribution of population growth rates instead of a single deterministic value.
* We then can randomly draw growth rate values from this distribution for each time-step in a population projection.
* The "spread" or uncertainty in the population size at a future time point depends on (i) the spread (variance) of the distribution and (ii) the amount of time elapsed. 
* We can repeatedly simulate a population projection (e.g. in R, or more laboriously in Excel) to get a feel for the likely fate of a population. E.g. "what percent of the projections show extinction within 50 years?".
* We can use this relatively simple and "unrealistic" model to nevertheless get an intuition about general trends in population dynamics and extinction risk.
* Extinction probability increases as (i) initial population size decreases; (ii) variance increases; (iii) growth rates decrease; (iv) the time frame increases.


## Solutions: Basic logistic population growth

You were asked to use the Excel sheet to answer some questions about logistic growth by examining the graphs.

**First – take a look at Graph 1**. 

*	*What is the maximum population size?* 
*	*How does this compare to carrying capacity (K)?*
*	*What do you predict to happen if you increase K to 300?*
*	*Try doing that. Were you correct?*

You should notice that when the population growth rate ($r_m$) is around 1 or lower, the maximum population size is the same as the carrying capacity ($K$). As you change $K$, this maximum population size will change accordingly. 

If $r_m$ is markedly greater than 1, then the population size can exceed the carrying capacity. This is because the population grows so fast that it “*overshoots*” carrying capacity and then fluctuates around K.

*	*At what time do you reach the maximum population size?* 
*	*If you halved growth rate (r_m) to 0.4, what do you think will happen to this time? *
*	*Try doing that. Were you correct?*

You should notice that the time taken to reach the maximum population size is related to the growth rate ($r_m$). As you increase $r_m$, the time taken to hit the maximum population size decreases. If you halve the growth rate, the time taken to reach maximum population size is doubled.

*	*What do you think will happen if you increase growth rate to 1.8?* 
*	*Try that… were you correct?*
*	*What do you notice about the population size through time?* 
*	*How does the maximum population size compare with the carrying capacity?* 
* *How would you describe the ‘dynamics’ of this population?*

You should notice that the population overshoots carrying capacity ($K$), then oscillates around $K$ with damped oscillations that gradually move towards $K$. Therefore if a population has even a moderate population growth rate, and if it has density-dependence, then it can fluctuate in numbers without any extrinsic factor (like weather) acting.

*	*What happens if you increase the growth rate even more, to 2 or 2.1?* 
*	*And even more to 2.8, 2.9 or 3?* 
*	*How would you describe these dynamics?* 
*	*Is there a limit to how high $r_m$ can be? (hint: populations go extinct if N < 0).*

You should notice that as you increase $r_m$ the nature of the oscillations changes. In fact, this is predictable:  If $r_m < 1.0$, then population will approach $K$ smoothly.

If $1.0 < r_m < 2.0$, then oscillations of decreasing amplitude around K.

If $2.0< r_m < 2.57$, then stable, cyclic oscillations around K . They can be 1 or 2+ point stable limit cycles.

If $r_m > 2.57$, then population will fluctuate chaotically.

If $r_m$ is too high, the population will fluctuate and crash to extinction.

*Compare the population trajectory in Graph 1 for populations with $r_m$= 2.8 and 2.81. Then compare the trajectories where you fix $r_m$ at 2.8 but vary initial population size by a small amount (e.g. 1). Imagine you were a population manager – would these populations be easy or hard to predict? What kinds of species have high population growth rates like these?*

When $r_m$ is high ($>2.57$) the population dynamics become extremely hard (impossible) to predict because they are chaotic. This means that even a very small change in $r_m$ (which could simply be measurement error) will mean that predicted population size next year is suddenly very different. This would cause big problems to a population manager.

Many pest species and diseases have very high population growth rates. For example, locusts, or measles. This is one reason why it is hard to predict when the next pest/disease outbreak will happen

**Now let’s turn to Graphs 2 and 3**

*In graph 2, notice that the per capita growth rate always declines linearly with population size ($N$). Where does it cross the x-axis line? Modify the carrying capacity ($K$) – what do you notice?*

The line describing per capita growth rate crosses the x-axis (population size) at $K$. i.e. if $K = 100$, the line crosses at 100. If you change $K$, the intercept on the axis also changes accordingly. The line intercepts the axis at this point no matter what the population growth rate is.

*Graph 3 is shaped like a parabola, starting with small values, increasing to a maximum, then declining to small values again. The peak of the parabola is at $K/2$ and the line crosses the y-axis at $0$ and $K$. Confirm to yourself, by changing the values for $r_m$ and $K$ that this is always the case.*

The pattern remains whatever the values of $K$, and $r_m$

*How would the same plots look for regular exponential growth?*

The equivalent plot (for Graph 2) for exponential growth would be a horizontal line - because population growth rate does NOT depend on population size.

## Solutions: Deeper into logistic growth

### Relationship between Logistic and Exponential growth equations

The logistic growth equation simplifies to become the exponential growth equation if you set $K$ to be infinite ($\infty$). The simplification goes like this:

1. $\frac{d N}{d t}=r N\left(1-\frac{N}{K}\right)$
2. $\frac{d N}{d t}=r N\left(1-\frac{N}{\infty}\right)$
3. $\frac{d N}{d t}=r N\left(1-0\right)$
4. $\frac{d N}{d t}=r N \times 1$
5. $\frac{d N}{d t}=r N$

This simplification also works with the discrete version of the equation, $N_{t+1}=N_{t}+r_{d} N_{t}\left(1-\frac{N_{t}}{K}\right)$.


### Type of dynamics depends on $r_m$.

As you increase $r_m$, the dynamics of the population changes. At low $r_m$ population size ($N$) simply converges on the carrying capacity, $K$. As $r_m$ you will see damped oscillations whereby $N$ overshoots $K$ and then oscillates and converges to $K$. Then you will see cycles where the population size oscillates *around* $K$. The cycles can be simple two-point cycles (where $N$ bounces between two points), or more complex with $N$ bouncing between four-points (or more). In fact, the critical values of $r_m$ that define the type of dynamics are fixed: if we know $r_m$ we can predict the type of dynamics.

The behaviour of the population dynamics depends only on $r_m$, not on $K$ or starting population size ($N_0$) (as long as $N_0 > K$).

### You can obtain parameters from graphs

You should notice that having some information about what the parameters are will allow you to sketch the dynamics. Conversely, if you have a graph showing aspects of the population dynamics, you could figure out what the parameters of the logistic equation are.

For Exponential growth, populaiton size is unlimited and will grow exponentially if $r$ is $>0$ (or $\lambda > 1$). Logistic growth will show some kind of limit (damped oscillation, or whatver), as the population size is attracted to $K$ in some way.

In logistic growth, the per capita growth rate declines as population size increases, and reaches $0$ when $N = K$. In exponential growth, the per capita growth rate remains constant and unaffected by $N$. Therefore the graphs of growth rate vs. N will be very different: Logistic = a negative slope, expontial = a horizontal line.

### Time lag

Time lagged density dependence results in oscillations. Therefore if we see oscillations in dynamics it could be due to a particular $r_m$ value or lagged density dependence.

### Cobweb diagram

Cobweb diagrams and bifurcation plots offer another way of visualising dynamics of populations (see the article about Chaos, by Mathiopoulos).

Chaotic dynamics are deterministic in the sense that if you have the same initial conditions you will get the same results (dynamics). However, small changes in any parameters ($N_0$, $K$, or $r_m$) will lead to very different dynamics - so in that sense, because of measurement error, the population dynamics would be very hard to predict in practice.

## Solutions: Life tables and survivorship types

The take home messages for this exercise are that life tables are a rich source of information on the life history of a population or species. From a simple accounting of ages at death and fertility we can obtain information about the "shape" of the survivorship trajectory: do most deaths happen early or late? Is mortality risk constant with age? We can also calculate measures including **generation time**, $R_0$ and population growth rate. You should know what these measures mean.


You should understand the relationship between mortality risk and survivorship curve. In other words, you should be able to describe, or do a rough sketch of mortality risk with age, if you have a survivorship curve (or vice versa). 

The completed Excel spreadsheet is [here](https://www.dropbox.com/s/j8uv2wf7nz0ygmp/Life%20tables%20exercise%20-%20complete.xlsx?dl=1). 



## Solutions: Matrix population modeling

The main take home messages for this class are that you should: 
(1) understand, and be able to draw or interpret life cycle diagram;
(2) be able to (roughly) parameterise a model shown in the life cycle diagram;
(3) be able to write out a matrix model (the square of numbers) for a given life cycle diagram (and *vice versa*).
(4) understand how population projection works, and to therefore interpret a figure or description showing a population projection.
(5) understand what an elasticity matrix tells us (it tells us the relative importance of the transitions for population growth)
(6) understand the concept of doing an LTRE to investigate management options.



## Solutions: Lotka-Volterra competition

You can find a completed Excel spreadsheet [here](https://www.dropbox.com/s/q1qoqxhnm82uugw/9.%20LV%20Competition.xlsx?dl=1).

The answers to the questions are [here](https://www.dropbox.com/s/oz2c10bmyf8t7s6/9.%20Answers%20to%20questions.pdf?dl=1).


## Solutions: Lotka-Volterra predator-prey dynamics

You can find a completed Excel spreadsheet [here](https://www.dropbox.com/s/wet7brtgxywdqi5/10.%20Pred-PreyDynamics.xlsx?dl=1).

The answers to the questions are [here](https://www.dropbox.com/s/mt43nvqu7cjif69/10.%20Answers%20to%20Pred-Prey%20exercise.pdf?dl=1).


## Solutions: From population biology to fitness

The matrix model with a trade off (increased juvenile survival, but reduced old adult survival) looks like this.

    A3 <- matrix(c(0.00, 5.00, 1.00, 
                   0.11, 0.80, 0.00, 
                   0.00, 0.10, 0.20), 
                byrow = TRUE, nrow = 3)
    
    eigs(A3)$lambda

We can compare the $\lambda$ value from this model to the original one to ask ourselves whether the large cost is worth paying for the small benefit. It turns out that it is. You can then ask how MUCH cost would be worth bearing, by repeating the exercise and slowly reducing old-adult survival until you reach the original $\lambda$ value.

You should find that the cost can be huge, and still worth bearing. In fact, you could reduce old adult survival to 0 and it is still worth doing! You can even reduce old-age adult reproduction without much effect on fitness.

HOWEVER, changes to prime age adults are much more important. You can only reduce survival to about 0.76 (from 0.8) before the cost is not worth bearing (population growth rate falls below that of the first baseline model). 

Thus, old-age costs are "worth it" while prime age costs are much more important. This finding is central to the evolution of senescence and life span, which we will cover later in the course.

## Solutions: Bug hunt camouflage

*	_What happens to the average colour of the bug population with time as you hunt?_

The colour evolves to become more similar to the background colour because you (the hunter) find it harder to find these better-camouflaged individuals.

*	_What happens to your hunting efficiency?_

Your hunting efficiency tends to decrease with time because the bugs are evolving to be harder to see. They are evolving camouflaged colours.

*	_Would you say that the bug population becomes worse or better adapted to their environment?_

The population becomes better-adapted to their environment with time.

*	_Can you explain how this happens?_

You (the hunter) kill the most obvious bugs first (i.e. those with contrasting colours to the background). These are the individuals that are not well-adapted to the environment. The survivors have offspring that are similar to them, while the ones you kill leave no offspring. So as time goes on, the population becomes dominated by individuals that are well-camouflaged.

*	_After simulating in one environment (e.g. poppy field) for a few minutes, pause then switch to another environment. Are the bugs now well- or poorly-adapted to their environment?_

Changing the environment means that the individuals are now porrly-adapted to their environment. This is because the individuals now find themselves in an environment that they did not evolve in. Their evolved camouflage does not work so well in a new environment.

*	_Do the genotypes of individuals change (e.g. with individual age)?_

No, individuals' genotypes are fixed. The change in the population occurs because of selection of individuals to reproduce. Better-adapted individuals are more likely to reproduce.

*	_Increasing the “max-mutation-step” makes bug offspring less like their parents. How do you think this will influence the speed of adaptation of the bugs?_

Increasing the amount of variation in offspring will tend to speed up adaptation. However, there are limits: too much variation can cause maladaptation of offspring. For example, if a parent is well-adapted (perfectly camouflaged), too much variation in offspring could lead to some offspring being poorly-camouflaged and therefore vulnerable to predation. 

## Solutions: Neutral or adaptive evolution in humans

The take home message here is that whether traits are adaptive or neutral depends on the environment. 

Consider genes that confer entibiotic resistance on bacteria. In the absence of antibiotics, these genes are not important and are not selected for. They still evolve (if they vary among individuals and are inherited), but this evolution is neutral with no selection. On the other hand, when antibiotics are introduced to the system, those same genes are strongly selected for and evolution of the genes for antibiotic resistance is now strongly adaptive. Context matters.

The same is the case for traits in humans. Assuming the the traits vary among individuals and are inherited, their neutrality or adaptiveness depends on their effect on fitness. If the traits have strong effects on fitness then they will be under strong selection but if they have weak or no effects on fitness they will evolve via neutral evolution.

Example traits that evolve via neutral evolution include fingerprint structure and iris structure. The detailed structures are not important to fitness, but are still genetically determined, and inherited.

Traits like muscle strength, running speed may have been important for fitness when they helped our ancestors obtain food. In those environments, they would have been under selection and therefore evolve via adaptive evolution. In more modern times, these selection pressures are weaker.



## Solutions: Hardy-Weinberg equilibrium

Answers to the Hardy-Weinberg questions.

Remember the basic formulas: 
$p^2 + 2pq + q^2 = 1$ and $p + q = 1$
  
$p$ = frequency of the dominant allele in the population 

$q$ = frequency of the recessive allele in the population

$p^2$ = percentage of homozygous dominant individuals 

$q^2$ = percentage of homozygous recessive individuals 

$2pq$ = percentage of heterozygous individuals 

### Problem 1

The frequency of the *aa* genotype: 36%, as given in the problem itself. 

The frequency of the *a* allele:  The frequency of aa is 36%, which means that $q^2 = 0.36$, by definition. If $q^2 = 0.36$, then $q = 0.6$. Since $q$ equals the frequency of the "a" allele, the frequency is 60%. 

The frequency of the *A* allele: Since $q = 0.6$, and $p + q = 1$, then $p = 0.4$; the frequency of *A* is equal to $p$ (see the basic H-W equations), so the answer is 40%. 

The frequencies of the genotypes *AA* and *Aa*: The frequency of *AA* is equal to $p^2$, and the frequency of *Aa* is equal to $2pq$. So, using the information above, the frequency of *AA* is 16% (i.e. $p^2 = 0.4 x 0.4 = 0.16$ and Aa is 48% ($2pq = 2 \times 0.4 \times 0.6 = 0.48$). 

The frequencies of the two possible phenotypes if *A* is completely dominant over *a*: Because *A* is totally dominate over *a*, the dominant phenotype will show if either the homozygous *AA* or heterozygous *Aa* genotypes occur. The recessive phenotype is controlled by the homozygous *aa* genotype. Therefore, the frequency of the dominant phenotype equals the sum of the frequencies of *AA* and *Aa*, and the recessive phenotype is simply the frequency of *aa*. Therefore, the dominant frequency is 64% and, in the first part of this question above, you have already shown that the recessive frequency is 36%. 

 
### Problem 2

9% = 0.09 = ss = $q^2$. To find $q$, simply take the square root of 0.09 to get 0.3. Since $p = 1 - 0.3$, then $p$ must equal 0.7. $2pq = 2 \times 0.7 \times 0.3 = 0.42$, so 42% of the population are heterozygotes (carriers). 

### Problem 3

The frequency of the recessive allele. Since we believe that the homozygous recessive for this gene ($q^2$) represents 4% (i.e. = 0.04), the square root ($q$) is therefore 0.2 (20%). 

The frequency of the dominant allele.  Since $q = 0.2$, and $p + q = 1$, then $p = 0.8$ (80%). 

The frequency of heterozygous individuals. The frequency of heterozygous individuals is equal to $2pq$. In this case, $2pq = 0.32$, which means that the frequency of individuals heterozygous for this gene is equal to 32% (i.e. $2 \times 0.8 \times 0.2) = 0.32$. 

### Problem 4

The first thing you'll need to do is obtain $p$ and $q$. So, since white is recessive (i.e. *bb*), and 40% of the butterflies are white, then *bb* = $q^2$ = 0.4. 
To determine $q$, which is the frequency of the recessive allele in the population,  take the square root of $q^2$ which is 0.632. So, $q = 0.63$. Since $p + q = 1$, then $p$ must be $1 - 0.63 = 0.37$. 

Now then, to answer our questions. First, what is the percentage of butterflies in the population that are heterozygous? Well, that would be $2pq$ so the answer is $2 \times 0.37\times 0.63 = 0.47$. Second, what is the frequency of homozygous dominant individuals? That would be $p^2$ or $0.37^2 = 0.14$.

## Solutions: How many eggs should a bird lay?

You can find a completed Excel spreadsheet [here](https://www.dropbox.com/s/tcpxmdfvm35jzgr/How%20many%20eggs%20-%20answers.xlsx?dl=1).

The take-home message is that the trade-off between number of eggs and juvenile survival leads to an optimum number of eggs required to maximise reproductive success (i.e. number of surviving chicks).

You can move this optimum if the trade-off is changed. For example, if you increase survival of the chicks from larger clutches, then the optimum number of eggs will increase.

This fact reminds us that the environment (e.g. predation risk and resource abundance) will be an important factor in determining the evolution of life history parameters (like average number of babies). 


## Solutions: Trade-offs and the force of selection

*Simulate this by adding 1 to fertility (mx) in year 1 (the benefit) but reducing survival to 0 (all die) at age 25 (the cost). What is the fitness of this strategy?*
  
Fitness (R0) would be 50.76 (compared to 49.81).

*By setting survival to 0 at other ages, determine how many years of life could be lost before this cost is no longer worth bearing. Is this surprising?*
  
You could “kill” the species at 18, losing 8 years of life, before the new strategy of a small increase in fertility at the expense of years of life at the end of life becomes unfavourable. In other words, a cost of losing 8 yrs of life is worth bearing if the benefit is an extra baby in year 1.


*Now reset everything (mx =10; survival = 0.8). Recall what fitness was when you added 1 to mx at age 1 (R0=50.811). 
If, instead of adding to mx at age 1 you were to increase mx at age 25, how much would you need to increase it to to reach this figure?* 

At age 25 you would need to increase Fertility from 10 to 222 to reach the same level of improvement in fitness as increasing Fertility from 10 to 11 at age 1.

*What about at age 20?*   10 to 80
*Age 15?* 10 to 33
*Age 10?*  10 to 18
*Age 5?* 10 to 13

*What do you notice?*

You should notice that changes made at younger ages have a bigger effect than those at older ages. I have plotted this to the right. The plot shows the amount of increase in fertility that would be required to raise fitness (R0) from 49.81 to >50.81 at ages 1 through to 25 (i.e. the figures you estimated above). You can see that you only need to change fertility a little bit at young ages, but you would need to make BIG changes at older ages. 

*Reset everything again (mx =10; survival = 0.8). Set mx from age 15 onwards to be 0. Now alter survival rate after this point (at ages 15-25). What happens to fitness?*
  
You should notice that any changes you make to survival AFTER reproduction has been completed will have no effect on fitness. In other words evolution “doesn’t care about you” after you have finished with reproduction.


## Making a phylogeny

[coming soon]

## Short answer exam discussion

[coming soon]

## The Red Queen game

[coming soon]