--- 
title: "BB512 - Population Biology and Evolution"
author: "Owen R. Jones (Course Coordinator)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
pandoc_args: --listings
output:
  bookdown::gitbook:
    config:
      toc:
        collapse: section
    includes:
      in_header: extras.css
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
    papersize: a4
  pdf_document:
    includes:
      in_header: preamble.tex
classoption: a4paper
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Course book for BB512 at the Biology Department, University of Southern Denmark"

---

```{r setOptions, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, message = FALSE
)
```

# Welcome to BB512


Welcome to the Population and Evolution course. 
The course, and this website, is divided into five parts:

1. Evolution by Natural Selection
2. Population Growth Models
3. Population Genetics and Evolution
4. Interactions Between Species and Community Structure
5. Animal Behaviour, Altruism and Sexual Selection

The recommended textbook is Neal (2018). Other useful textbooks, that are NOT mandatory, but could be useful are Gotelli (2008) and Stearns & Hoekstra (2005).


* Neal, D. (2018). *Introduction to Population Biology* (2nd ed.). Cambridge: Cambridge University Press. doi:10.1017/9781139107976
* Gotelli, NJ (2008) *A Primer of Ecology*. Fourth Edition, Sinauer Associates. ISBN: 978-0878933181
* Stearns, SC & Hoekstra, RF (2005) *Evolution: An Introduction*. 2nd Edition, Oxford University Press. ISBN: 978-0199255634

In addition to this, I will provide a reading list of journal articles that are relevant to the material. These are optional, but highly recommended because they give extra context and background to the course and show you how the theory is used in recent research.

## This website and other course materials

This website holds most of the materials you need for the practical exercises you will do during the course. You will also find the [Schedule](https://jonesor.github.io/BB512_Book/schedule.html) here.

We may not do ALL of these exercises, but you are welcome to do ones we miss in your own time.

You will find other materials via itsLearning. 

For most classes you will need your personal laptops: Please bring them to class (and remember a power supply!).

## Expectations

There are lectures and exercise sessions on the course. The exercise sessions are designed to help you understand the subject better and I expect students to attend and actively participate in both. There will also be some multiple choice quizzes (e-tests) during the semester. These are intended to help you figure out whether you know the material, and whether there are areas you need to revisit. They do not contribute to your final grade, but I hope you will attempt them. They will definitely increase your understanding of the material. Note that the final assessment will be a similar format!

I expect students to make every effort to keep up with the core reading (mainly the textbook chapters), and to ask questions where they don’t understand.

## Your feedback

I would really like your feedback on how the course is progressing so I can address any issues that come up as soon as possible. To help with this I have created a simple Google Form: http://goo.gl/gy2Q6B. You can use this to send me (Owen) comments (anonymously if you wish) at any time in the course. I promise to do my best to resolve any problems.
 
## Assessment

The assessment for the course will be an electronic exam held next January with multiple choice and short answer questions. It is worth noting that exam format will be similar to the quizzes mentioned above. The exact date is not yet set.


## Instructors

The instructors of the course are:

*	[Owen Jones](https://portal.findresearcher.sdu.dk/en/persons/jones), Associate Professor, jones@biology.sdu.dk 
*	[Thomas Bjørneboe Berg](https://portal.findresearcher.sdu.dk/en/persons/thomasbb), Associate Prof./Senior Scientist at Naturama, thomas@naturama.dk  

If you have any problems accessing materials, or have any questions regarding the course feel free to send me (Owen) an email, or make a comment in the form I mentioned above. You can also make an appointment to see me via Zoom or in my office if necessary*. PLEASE REMEMBER to tell me which course you are referring to if you send an email!

Owen Jones, course coordinator - [jones@biology.sdu.dk](mailto:jones@biology.sdu.dk ) 

Office location: [V12-410b-2](https://clients.mapsindoors.com/sdu/573f26e4bc1f571b08094312/details/563cb94f423b7d0540c9a605)

## Software

We will use Excel and R/RStudio during this course.

### Excel

I expect you will already have Excel installed, so there is not much to say here.

Be aware that Excel differs depending on the language it is localised in. For example, Danish vs. English. This means that some of the commands might differ between version. 
See [here](https://easy-excel.com/excel-in-other-languages/excel-formulas-in-danish/) for examples.

### R and RStudio

R and RStudio are two separate pieces of software. RStudio is a user-friendly interface to talk to R, it cannot work if you have not got R installed. So, when you install these two programs, install R first, then RStudio.

Already have them installed?  I strongly recommend to update to the latest versions of R, which you can download [here](https://cran.r-project.org) and RStudio Desktop, which you can find [here](https://www.rstudio.com/products/rstudio/). 


If you are unsure whether you should update your R or RStudio try the following code. If it produces a nice graph, then your R is sufficiently up-to-date. If there are error messages, then you probably need to update R.

```
install.packages("popdemo")
library(popdemo)

A <- matrix(c(0,1,2,0.5,0.1,0,0,0.6,0.6), byrow=TRUE, ncol=3)

pr <- project(A, vector="n", time=10)
plot(pr)
```


```{block, type="do-something"}
**Note:** The website is a "work in progress" and might change during the course as I add material. The latest version can always be found at the website.

Please let me know ([jones@biology.sdu.dk](mailto:jones@biology.sdu.dk)) if you spot any errors, or have any suggestions for improvement.
```

