<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>25 Solutions and “take-home” messages | BB512 - Population Biology and Evolution</title>
  <meta name="description" content="Course book for BB512 at the Biology Department, University of Southern Denmark" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="25 Solutions and “take-home” messages | BB512 - Population Biology and Evolution" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course book for BB512 at the Biology Department, University of Southern Denmark" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="25 Solutions and “take-home” messages | BB512 - Population Biology and Evolution" />
  
  <meta name="twitter:description" content="Course book for BB512 at the Biology Department, University of Southern Denmark" />
  

<meta name="author" content="Owen R. Jones (Course Coordinator)" />


<meta name="date" content="2026-02-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="part-6.html"/>
<link rel="next" href="results-of-the-hawk-dove-games.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>
<style type="text/css">

.warning-box {
  border: 3px solid #e60000;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

.advanced-box {
  border: 3px solid #268bd2;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

.do-something {
  border: 3px solid #803e00;
  margin:  25px;
  padding: 10px 10px 5px 10px;
  border-radius: 6px 6px 6px 6px;
}

</style>





<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BB512</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome to BB512</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#how-to-use-this-book"><i class="fa fa-check"></i><b>1.1</b> How to use this book</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#parts-overview"><i class="fa fa-check"></i><b>1.2</b> Parts overview</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#this-website-and-other-course-materials"><i class="fa fa-check"></i><b>1.3</b> This website and other course materials</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#expectations"><i class="fa fa-check"></i><b>1.4</b> Expectations</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>1.5</b> Assessment</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#instructors"><i class="fa fa-check"></i><b>1.6</b> Instructors</a></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#software"><i class="fa fa-check"></i><b>1.7</b> Software</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="index.html"><a href="index.html#excel"><i class="fa fa-check"></i><b>1.7.1</b> Excel</a></li>
<li class="chapter" data-level="1.7.2" data-path="index.html"><a href="index.html#r-and-rstudio"><i class="fa fa-check"></i><b>1.7.2</b> R and RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#schedule"><i class="fa fa-check"></i><b>1.8</b> Schedule</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-1.html"><a href="part-1.html"><i class="fa fa-check"></i>Part 1: Evolution by Natural Selection</a></li>
<li class="chapter" data-level="2" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html"><i class="fa fa-check"></i><b>2</b> The Blind Watchmaker</a>
<ul>
<li class="chapter" data-level="2.1" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#background"><i class="fa fa-check"></i><b>2.1</b> Background</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#randomness-and-selection"><i class="fa fa-check"></i><b>2.1.1</b> Randomness and Selection</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#learning-outcomes"><i class="fa fa-check"></i><b>2.2</b> Learning outcomes</a></li>
<li class="chapter" data-level="2.3" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#worked-example"><i class="fa fa-check"></i><b>2.3</b> Worked example</a></li>
<li class="chapter" data-level="2.4" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#your-task"><i class="fa fa-check"></i><b>2.4</b> Your task</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#the-code"><i class="fa fa-check"></i><b>2.4.1</b> The code</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#how-the-simulation-works."><i class="fa fa-check"></i><b>2.5</b> How the simulation works.</a></li>
<li class="chapter" data-level="2.6" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#questions"><i class="fa fa-check"></i><b>2.6</b> Questions</a></li>
<li class="chapter" data-level="2.7" data-path="the-blind-watchmaker.html"><a href="the-blind-watchmaker.html#takeaways"><i class="fa fa-check"></i><b>2.7</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html"><i class="fa fa-check"></i><b>3</b> Bug hunt camouflage (NetLogo)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html#background-1"><i class="fa fa-check"></i><b>3.1</b> Background</a></li>
<li class="chapter" data-level="3.2" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html#learning-outcomes-1"><i class="fa fa-check"></i><b>3.2</b> Learning outcomes</a></li>
<li class="chapter" data-level="3.3" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html#your-task-1"><i class="fa fa-check"></i><b>3.3</b> Your task</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html#getting-started"><i class="fa fa-check"></i><b>3.3.1</b> Getting started</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html#questions-1"><i class="fa fa-check"></i><b>3.4</b> Questions</a></li>
<li class="chapter" data-level="3.5" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html#worked-example-1"><i class="fa fa-check"></i><b>3.5</b> Worked example</a></li>
<li class="chapter" data-level="3.6" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html#details-about-colours-optional"><i class="fa fa-check"></i><b>3.6</b> Details about colours (optional)</a></li>
<li class="chapter" data-level="3.7" data-path="bug-hunt-camouflage-netlogo.html"><a href="bug-hunt-camouflage-netlogo.html#takeaways-1"><i class="fa fa-check"></i><b>3.7</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-2.html"><a href="part-2.html"><i class="fa fa-check"></i>Part 2: Population Growth Models</a></li>
<li class="chapter" data-level="4" data-path="geometric-growth.html"><a href="geometric-growth.html"><i class="fa fa-check"></i><b>4</b> Geometric growth</a>
<ul>
<li class="chapter" data-level="4.1" data-path="geometric-growth.html"><a href="geometric-growth.html#background-2"><i class="fa fa-check"></i><b>4.1</b> Background</a></li>
<li class="chapter" data-level="4.2" data-path="geometric-growth.html"><a href="geometric-growth.html#worked-example-2"><i class="fa fa-check"></i><b>4.2</b> Worked example</a></li>
<li class="chapter" data-level="4.3" data-path="geometric-growth.html"><a href="geometric-growth.html#your-task-2"><i class="fa fa-check"></i><b>4.3</b> Your task</a></li>
<li class="chapter" data-level="4.4" data-path="geometric-growth.html"><a href="geometric-growth.html#questions-2"><i class="fa fa-check"></i><b>4.4</b> Questions</a></li>
<li class="chapter" data-level="4.5" data-path="geometric-growth.html"><a href="geometric-growth.html#takeaways-2"><i class="fa fa-check"></i><b>4.5</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estimating-population-growth-rate.html"><a href="estimating-population-growth-rate.html"><i class="fa fa-check"></i><b>5</b> Estimating Population Growth Rate</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estimating-population-growth-rate.html"><a href="estimating-population-growth-rate.html#background-3"><i class="fa fa-check"></i><b>5.1</b> Background</a></li>
<li class="chapter" data-level="5.2" data-path="estimating-population-growth-rate.html"><a href="estimating-population-growth-rate.html#worked-example-3"><i class="fa fa-check"></i><b>5.2</b> Worked example</a></li>
<li class="chapter" data-level="5.3" data-path="estimating-population-growth-rate.html"><a href="estimating-population-growth-rate.html#your-task-3"><i class="fa fa-check"></i><b>5.3</b> Your task</a></li>
<li class="chapter" data-level="5.4" data-path="estimating-population-growth-rate.html"><a href="estimating-population-growth-rate.html#questions-3"><i class="fa fa-check"></i><b>5.4</b> Questions</a></li>
<li class="chapter" data-level="5.5" data-path="estimating-population-growth-rate.html"><a href="estimating-population-growth-rate.html#takeaways-3"><i class="fa fa-check"></i><b>5.5</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="stochastic-population-growth.html"><a href="stochastic-population-growth.html"><i class="fa fa-check"></i><b>6</b> Stochastic population growth</a>
<ul>
<li class="chapter" data-level="6.1" data-path="stochastic-population-growth.html"><a href="stochastic-population-growth.html#background-4"><i class="fa fa-check"></i><b>6.1</b> Background</a></li>
<li class="chapter" data-level="6.2" data-path="stochastic-population-growth.html"><a href="stochastic-population-growth.html#worked-example-4"><i class="fa fa-check"></i><b>6.2</b> Worked example</a></li>
<li class="chapter" data-level="6.3" data-path="stochastic-population-growth.html"><a href="stochastic-population-growth.html#your-task-4"><i class="fa fa-check"></i><b>6.3</b> Your task</a></li>
<li class="chapter" data-level="6.4" data-path="stochastic-population-growth.html"><a href="stochastic-population-growth.html#simulations-in-r"><i class="fa fa-check"></i><b>6.4</b> Simulations in R</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="stochastic-population-growth.html"><a href="stochastic-population-growth.html#example-stochastic-trajectories"><i class="fa fa-check"></i><b>6.4.1</b> Example stochastic trajectories</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="stochastic-population-growth.html"><a href="stochastic-population-growth.html#questions-4"><i class="fa fa-check"></i><b>6.5</b> Questions</a></li>
<li class="chapter" data-level="6.6" data-path="stochastic-population-growth.html"><a href="stochastic-population-growth.html#takeaways-4"><i class="fa fa-check"></i><b>6.6</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html"><i class="fa fa-check"></i><b>7</b> Basic logistic population growth</a>
<ul>
<li class="chapter" data-level="7.1" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#background-5"><i class="fa fa-check"></i><b>7.1</b> Background</a></li>
<li class="chapter" data-level="7.2" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#worked-example-5"><i class="fa fa-check"></i><b>7.2</b> Worked example</a></li>
<li class="chapter" data-level="7.3" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#your-task-5"><i class="fa fa-check"></i><b>7.3</b> Your Task</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#graph-1-population-size-through-time"><i class="fa fa-check"></i><b>7.3.1</b> Graph 1: Population Size Through Time</a></li>
<li class="chapter" data-level="7.3.2" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#graph-2-per-capita-growth-rate-vs.-population-size"><i class="fa fa-check"></i><b>7.3.2</b> Graph 2: Per Capita Growth Rate vs. Population Size</a></li>
<li class="chapter" data-level="7.3.3" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#reflection-on-graph-2"><i class="fa fa-check"></i><b>7.3.3</b> Reflection on Graph 2</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#takeaways-5"><i class="fa fa-check"></i><b>7.4</b> Takeaways</a></li>
<li class="chapter" data-level="7.5" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#questions-5"><i class="fa fa-check"></i><b>7.5</b> Questions</a></li>
<li class="chapter" data-level="7.6" data-path="basic-logistic-population-growth.html"><a href="basic-logistic-population-growth.html#optional-do-this-in-r."><i class="fa fa-check"></i><b>7.6</b> Optional: Do this in R.</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="deeper-into-logistic-growth.html"><a href="deeper-into-logistic-growth.html"><i class="fa fa-check"></i><b>8</b> Deeper into Logistic Growth</a>
<ul>
<li class="chapter" data-level="8.1" data-path="deeper-into-logistic-growth.html"><a href="deeper-into-logistic-growth.html#background-6"><i class="fa fa-check"></i><b>8.1</b> Background</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="deeper-into-logistic-growth.html"><a href="deeper-into-logistic-growth.html#linking-logistic-and-exponential-growth-models"><i class="fa fa-check"></i><b>8.1.1</b> Linking Logistic and Exponential Growth Models</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="deeper-into-logistic-growth.html"><a href="deeper-into-logistic-growth.html#worked-example-6"><i class="fa fa-check"></i><b>8.2</b> Worked example</a></li>
<li class="chapter" data-level="8.3" data-path="deeper-into-logistic-growth.html"><a href="deeper-into-logistic-growth.html#your-task-6"><i class="fa fa-check"></i><b>8.3</b> Your Task</a></li>
<li class="chapter" data-level="8.4" data-path="deeper-into-logistic-growth.html"><a href="deeper-into-logistic-growth.html#questions-6"><i class="fa fa-check"></i><b>8.4</b> Questions</a></li>
<li class="chapter" data-level="8.5" data-path="deeper-into-logistic-growth.html"><a href="deeper-into-logistic-growth.html#takeaways-6"><i class="fa fa-check"></i><b>8.5</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="life-tables-and-survivorship-types.html"><a href="life-tables-and-survivorship-types.html"><i class="fa fa-check"></i><b>9</b> Life tables and survivorship types</a>
<ul>
<li class="chapter" data-level="9.1" data-path="life-tables-and-survivorship-types.html"><a href="life-tables-and-survivorship-types.html#background-7"><i class="fa fa-check"></i><b>9.1</b> Background</a></li>
<li class="chapter" data-level="9.2" data-path="life-tables-and-survivorship-types.html"><a href="life-tables-and-survivorship-types.html#worked-example-7"><i class="fa fa-check"></i><b>9.2</b> Worked example</a></li>
<li class="chapter" data-level="9.3" data-path="life-tables-and-survivorship-types.html"><a href="life-tables-and-survivorship-types.html#your-task-7"><i class="fa fa-check"></i><b>9.3</b> Your task</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="life-tables-and-survivorship-types.html"><a href="life-tables-and-survivorship-types.html#life-table"><i class="fa fa-check"></i><b>9.3.1</b> Life table</a></li>
<li class="chapter" data-level="9.3.2" data-path="life-tables-and-survivorship-types.html"><a href="life-tables-and-survivorship-types.html#survivorship-curves"><i class="fa fa-check"></i><b>9.3.2</b> Survivorship curves</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="life-tables-and-survivorship-types.html"><a href="life-tables-and-survivorship-types.html#questions-7"><i class="fa fa-check"></i><b>9.4</b> Questions</a></li>
<li class="chapter" data-level="9.5" data-path="life-tables-and-survivorship-types.html"><a href="life-tables-and-survivorship-types.html#takeaways-7"><i class="fa fa-check"></i><b>9.5</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html"><i class="fa fa-check"></i><b>10</b> Matrix population modelling</a>
<ul>
<li class="chapter" data-level="10.1" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#background-8"><i class="fa fa-check"></i><b>10.1</b> Background</a></li>
<li class="chapter" data-level="10.2" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#your-task-8"><i class="fa fa-check"></i><b>10.2</b> Your task</a></li>
<li class="chapter" data-level="10.3" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#using-r-for-matrix-modelling"><i class="fa fa-check"></i><b>10.3</b> Using R for matrix modelling</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#package-setup-if-needed"><i class="fa fa-check"></i><b>10.3.1</b> Package setup (if needed)</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#projecting-the-population"><i class="fa fa-check"></i><b>10.4</b> Projecting the population</a></li>
<li class="chapter" data-level="10.5" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#elasticity"><i class="fa fa-check"></i><b>10.5</b> Elasticity</a></li>
<li class="chapter" data-level="10.6" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#life-table-response-experiment-ltre"><i class="fa fa-check"></i><b>10.6</b> Life table response experiment (LTRE)</a></li>
<li class="chapter" data-level="10.7" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#your-turn"><i class="fa fa-check"></i><b>10.7</b> Your turn…</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#an-evolutionary-experiment"><i class="fa fa-check"></i><b>10.7.1</b> An evolutionary experiment</a></li>
<li class="chapter" data-level="10.7.2" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#questions-8"><i class="fa fa-check"></i><b>10.7.2</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="matrix-population-modelling.html"><a href="matrix-population-modelling.html#takeaways-8"><i class="fa fa-check"></i><b>10.8</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="pre--and-post-reproduction-census.html"><a href="pre--and-post-reproduction-census.html"><i class="fa fa-check"></i><b>11</b> Pre- and Post-reproduction census</a>
<ul>
<li class="chapter" data-level="11.1" data-path="pre--and-post-reproduction-census.html"><a href="pre--and-post-reproduction-census.html#background-9"><i class="fa fa-check"></i><b>11.1</b> Background</a></li>
<li class="chapter" data-level="11.2" data-path="pre--and-post-reproduction-census.html"><a href="pre--and-post-reproduction-census.html#learning-outcomes-2"><i class="fa fa-check"></i><b>11.2</b> Learning outcomes</a></li>
<li class="chapter" data-level="11.3" data-path="pre--and-post-reproduction-census.html"><a href="pre--and-post-reproduction-census.html#worked-example-8"><i class="fa fa-check"></i><b>11.3</b> Worked example</a></li>
<li class="chapter" data-level="11.4" data-path="pre--and-post-reproduction-census.html"><a href="pre--and-post-reproduction-census.html#your-task-9"><i class="fa fa-check"></i><b>11.4</b> Your task</a></li>
<li class="chapter" data-level="11.5" data-path="pre--and-post-reproduction-census.html"><a href="pre--and-post-reproduction-census.html#takeaways-9"><i class="fa fa-check"></i><b>11.5</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html"><i class="fa fa-check"></i><b>12</b> Life Table Response Experiments</a>
<ul>
<li class="chapter" data-level="12.1" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#introduction"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#learning-outcomes-3"><i class="fa fa-check"></i><b>12.2</b> Learning outcomes</a></li>
<li class="chapter" data-level="12.3" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#set-up"><i class="fa fa-check"></i><b>12.3</b> Set up</a></li>
<li class="chapter" data-level="12.4" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#a-worked-example"><i class="fa fa-check"></i><b>12.4</b> A worked example</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#comparing-matrices"><i class="fa fa-check"></i><b>12.4.1</b> Comparing matrices</a></li>
<li class="chapter" data-level="12.4.2" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#contributions-from-individual-matrix-elements"><i class="fa fa-check"></i><b>12.4.2</b> Contributions from individual matrix elements</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#relationship-with-elasticity-analysis"><i class="fa fa-check"></i><b>12.5</b> Relationship with elasticity analysis</a></li>
<li class="chapter" data-level="12.6" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#your-task-10"><i class="fa fa-check"></i><b>12.6</b> Your task</a></li>
<li class="chapter" data-level="12.7" data-path="life-table-response-experiments.html"><a href="life-table-response-experiments.html#takeaways-10"><i class="fa fa-check"></i><b>12.7</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="how-many-eggs-should-a-bird-lay.html"><a href="how-many-eggs-should-a-bird-lay.html"><i class="fa fa-check"></i><b>13</b> How many eggs should a bird lay?</a>
<ul>
<li class="chapter" data-level="13.1" data-path="how-many-eggs-should-a-bird-lay.html"><a href="how-many-eggs-should-a-bird-lay.html#background-10"><i class="fa fa-check"></i><b>13.1</b> Background</a></li>
<li class="chapter" data-level="13.2" data-path="how-many-eggs-should-a-bird-lay.html"><a href="how-many-eggs-should-a-bird-lay.html#worked-example-9"><i class="fa fa-check"></i><b>13.2</b> Worked example</a></li>
<li class="chapter" data-level="13.3" data-path="how-many-eggs-should-a-bird-lay.html"><a href="how-many-eggs-should-a-bird-lay.html#your-task-11"><i class="fa fa-check"></i><b>13.3</b> Your task</a></li>
<li class="chapter" data-level="13.4" data-path="how-many-eggs-should-a-bird-lay.html"><a href="how-many-eggs-should-a-bird-lay.html#questions-9"><i class="fa fa-check"></i><b>13.4</b> Questions</a></li>
<li class="chapter" data-level="13.5" data-path="how-many-eggs-should-a-bird-lay.html"><a href="how-many-eggs-should-a-bird-lay.html#takeaways-11"><i class="fa fa-check"></i><b>13.5</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="trade-offs-and-the-declining-force-of-selection.html"><a href="trade-offs-and-the-declining-force-of-selection.html"><i class="fa fa-check"></i><b>14</b> Trade-offs and the declining force of selection</a>
<ul>
<li class="chapter" data-level="14.1" data-path="trade-offs-and-the-declining-force-of-selection.html"><a href="trade-offs-and-the-declining-force-of-selection.html#background-11"><i class="fa fa-check"></i><b>14.1</b> Background</a></li>
<li class="chapter" data-level="14.2" data-path="trade-offs-and-the-declining-force-of-selection.html"><a href="trade-offs-and-the-declining-force-of-selection.html#worked-example-10"><i class="fa fa-check"></i><b>14.2</b> Worked example</a></li>
<li class="chapter" data-level="14.3" data-path="trade-offs-and-the-declining-force-of-selection.html"><a href="trade-offs-and-the-declining-force-of-selection.html#your-task-12"><i class="fa fa-check"></i><b>14.3</b> Your task</a></li>
<li class="chapter" data-level="14.4" data-path="trade-offs-and-the-declining-force-of-selection.html"><a href="trade-offs-and-the-declining-force-of-selection.html#exploring-different-life-history-strategies"><i class="fa fa-check"></i><b>14.4</b> Exploring different life history strategies</a></li>
<li class="chapter" data-level="14.5" data-path="trade-offs-and-the-declining-force-of-selection.html"><a href="trade-offs-and-the-declining-force-of-selection.html#questions-10"><i class="fa fa-check"></i><b>14.5</b> Questions</a></li>
<li class="chapter" data-level="14.6" data-path="trade-offs-and-the-declining-force-of-selection.html"><a href="trade-offs-and-the-declining-force-of-selection.html#takeaways-12"><i class="fa fa-check"></i><b>14.6</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html"><i class="fa fa-check"></i><b>15</b> Matrix Population Models (MPMs): Projection and Simulation</a>
<ul>
<li class="chapter" data-level="15.1" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#what-is-a-matrix-population-model"><i class="fa fa-check"></i><b>15.1</b> What is a matrix population model?</a></li>
<li class="chapter" data-level="15.2" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#the-projection-interval-delta-t"><i class="fa fa-check"></i><b>15.2</b> The projection interval (\(\Delta t\))</a></li>
<li class="chapter" data-level="15.3" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#the-population-vector"><i class="fa fa-check"></i><b>15.3</b> The population vector</a></li>
<li class="chapter" data-level="15.4" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#the-projection-matrix"><i class="fa fa-check"></i><b>15.4</b> The projection matrix</a></li>
<li class="chapter" data-level="15.5" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#a-simple-3-stage-model"><i class="fa fa-check"></i><b>15.5</b> A simple 3-stage model</a></li>
<li class="chapter" data-level="15.6" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#projection-projecting-mathbfn_t-forward"><i class="fa fa-check"></i><b>15.6</b> Projection: projecting \(\mathbf{n}_t\) forward</a></li>
<li class="chapter" data-level="15.7" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#define-vital-rates-and-build-mathbfa"><i class="fa fa-check"></i><b>15.7</b> Define vital rates and build \(\mathbf{A}\)</a></li>
<li class="chapter" data-level="15.8" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#define-an-initial-population-vector-mathbfn_0"><i class="fa fa-check"></i><b>15.8</b> Define an initial population vector \(\mathbf{n}_0\)</a></li>
<li class="chapter" data-level="15.9" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#one-step-projection"><i class="fa fa-check"></i><b>15.9</b> One-step projection</a></li>
<li class="chapter" data-level="15.10" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#project-for-many-years-deterministic"><i class="fa fa-check"></i><b>15.10</b> Project for many years (deterministic)</a>
<ul>
<li class="chapter" data-level="15.10.1" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#plot-totals-and-stage-trajectories"><i class="fa fa-check"></i><b>15.10.1</b> Plot totals and stage trajectories</a></li>
</ul></li>
<li class="chapter" data-level="15.11" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#long-term-growth-rate-lambda"><i class="fa fa-check"></i><b>15.11</b> Long-term growth rate (\(\lambda\))</a></li>
<li class="chapter" data-level="15.12" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#simulation-adding-stochasticity-and-management-actions"><i class="fa fa-check"></i><b>15.12</b> Simulation: adding stochasticity and management actions</a>
<ul>
<li class="chapter" data-level="15.12.1" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#one-simulated-trajectory-no-culling"><i class="fa fa-check"></i><b>15.12.1</b> One simulated trajectory (no culling)</a></li>
<li class="chapter" data-level="15.12.2" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#add-a-culling-intervention"><i class="fa fa-check"></i><b>15.12.2</b> Add a culling intervention</a></li>
<li class="chapter" data-level="15.12.3" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#many-replicates-uncertainty-bands"><i class="fa fa-check"></i><b>15.12.3</b> Many replicates (uncertainty bands)</a></li>
</ul></li>
<li class="chapter" data-level="15.13" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#student-exercises-for-a-class-handout"><i class="fa fa-check"></i><b>15.13</b> Student exercises (for a class handout)</a>
<ul>
<li class="chapter" data-level="15.13.1" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#exercise-projection-interval-sanity-check"><i class="fa fa-check"></i><b>15.13.1</b> Exercise: Projection interval sanity check</a></li>
<li class="chapter" data-level="15.13.2" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#exercise-change-one-vital-rate-and-re-run-projections"><i class="fa fa-check"></i><b>15.13.2</b> Exercise: Change one vital rate and re-run projections</a></li>
<li class="chapter" data-level="15.13.3" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#exercise-culling-as-management"><i class="fa fa-check"></i><b>15.13.3</b> Exercise: Culling as management</a></li>
<li class="chapter" data-level="15.13.4" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#exercise-contraception-treatment-reduced-fecundity"><i class="fa fa-check"></i><b>15.13.4</b> Exercise: Contraception treatment (reduced fecundity)</a></li>
</ul></li>
<li class="chapter" data-level="15.14" data-path="matrix-population-models-mpms-projection-and-simulation.html"><a href="matrix-population-models-mpms-projection-and-simulation.html#notes-and-extensions"><i class="fa fa-check"></i><b>15.14</b> Notes and extensions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-3.html"><a href="part-3.html"><i class="fa fa-check"></i>Part 3: Population Genetics and Evolution</a></li>
<li class="chapter" data-level="16" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html"><i class="fa fa-check"></i><b>16</b> Hardy-Weinberg equilibrium</a>
<ul>
<li class="chapter" data-level="16.1" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#background-12"><i class="fa fa-check"></i><b>16.1</b> Background</a></li>
<li class="chapter" data-level="16.2" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#assumptions-of-hardy-weinberg-equilibrium"><i class="fa fa-check"></i><b>16.2</b> Assumptions of Hardy-Weinberg Equilibrium</a></li>
<li class="chapter" data-level="16.3" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#worked-example-11"><i class="fa fa-check"></i><b>16.3</b> Worked example</a></li>
<li class="chapter" data-level="16.4" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#your-task-13"><i class="fa fa-check"></i><b>16.4</b> Your task</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#problem-1."><i class="fa fa-check"></i><b>16.4.1</b> Problem #1.</a></li>
<li class="chapter" data-level="16.4.2" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#problem-2."><i class="fa fa-check"></i><b>16.4.2</b> Problem #2.</a></li>
<li class="chapter" data-level="16.4.3" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#problem-3."><i class="fa fa-check"></i><b>16.4.3</b> Problem #3.</a></li>
<li class="chapter" data-level="16.4.4" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#problem-4."><i class="fa fa-check"></i><b>16.4.4</b> Problem #4.</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="hardy-weinberg-equilibrium.html"><a href="hardy-weinberg-equilibrium.html#takeaways-13"><i class="fa fa-check"></i><b>16.5</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html"><i class="fa fa-check"></i><b>17</b> The Gene Pool Model</a>
<ul>
<li class="chapter" data-level="17.1" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#background-13"><i class="fa fa-check"></i><b>17.1</b> Background</a></li>
<li class="chapter" data-level="17.2" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#worked-example-12"><i class="fa fa-check"></i><b>17.2</b> Worked example</a></li>
<li class="chapter" data-level="17.3" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#your-task-14"><i class="fa fa-check"></i><b>17.3</b> Your task</a></li>
<li class="chapter" data-level="17.4" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#a-simple-model"><i class="fa fa-check"></i><b>17.4</b> A simple model</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#the-gene-pool"><i class="fa fa-check"></i><b>17.4.1</b> The gene pool</a></li>
<li class="chapter" data-level="17.4.2" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#projecting-allele-frequency-over-one-time-step."><i class="fa fa-check"></i><b>17.4.2</b> Projecting allele frequency over one time step.</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#simulation-of-allele-frequency-through-time"><i class="fa fa-check"></i><b>17.5</b> Simulation of allele frequency through time</a></li>
<li class="chapter" data-level="17.6" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#bottlenecks"><i class="fa fa-check"></i><b>17.6</b> Bottlenecks</a></li>
<li class="chapter" data-level="17.7" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#conclusions"><i class="fa fa-check"></i><b>17.7</b> Conclusions</a></li>
<li class="chapter" data-level="17.8" data-path="the-gene-pool-model.html"><a href="the-gene-pool-model.html#takeaways-14"><i class="fa fa-check"></i><b>17.8</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html"><a href="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html"><i class="fa fa-check"></i><b>18</b> Neutral or Adaptive Evolution in Humans: What Drives Evolution of Our Traits?</a>
<ul>
<li class="chapter" data-level="18.1" data-path="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html"><a href="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html#background-14"><i class="fa fa-check"></i><b>18.1</b> Background</a></li>
<li class="chapter" data-level="18.2" data-path="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html"><a href="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html#worked-example-13"><i class="fa fa-check"></i><b>18.2</b> Worked example</a></li>
<li class="chapter" data-level="18.3" data-path="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html"><a href="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html#your-task-30-minutes"><i class="fa fa-check"></i><b>18.3</b> Your task (30 minutes)</a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html"><a href="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html#the-traits"><i class="fa fa-check"></i><b>18.3.1</b> The traits</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html"><a href="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html#discussion-timing-15-minutes"><i class="fa fa-check"></i><b>18.4</b> Discussion (Timing: 15 minutes)</a></li>
<li class="chapter" data-level="18.5" data-path="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html"><a href="neutral-or-adaptive-evolution-in-humans-what-drives-evolution-of-our-traits.html#takeaways-15"><i class="fa fa-check"></i><b>18.5</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="heritability-from-a-linear-regression.html"><a href="heritability-from-a-linear-regression.html"><i class="fa fa-check"></i><b>19</b> Heritability from a linear regression</a>
<ul>
<li class="chapter" data-level="19.1" data-path="heritability-from-a-linear-regression.html"><a href="heritability-from-a-linear-regression.html#background-15"><i class="fa fa-check"></i><b>19.1</b> Background</a></li>
<li class="chapter" data-level="19.2" data-path="heritability-from-a-linear-regression.html"><a href="heritability-from-a-linear-regression.html#worked-example-14"><i class="fa fa-check"></i><b>19.2</b> Worked example</a></li>
<li class="chapter" data-level="19.3" data-path="heritability-from-a-linear-regression.html"><a href="heritability-from-a-linear-regression.html#your-task-15"><i class="fa fa-check"></i><b>19.3</b> Your Task</a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="heritability-from-a-linear-regression.html"><a href="heritability-from-a-linear-regression.html#estimating-heritability-15-minutes"><i class="fa fa-check"></i><b>19.3.1</b> Estimating heritability (15 minutes)</a></li>
<li class="chapter" data-level="19.3.2" data-path="heritability-from-a-linear-regression.html"><a href="heritability-from-a-linear-regression.html#comparative-analysis-10-minutes"><i class="fa fa-check"></i><b>19.3.2</b> Comparative Analysis (10 minutes)</a></li>
<li class="chapter" data-level="19.3.3" data-path="heritability-from-a-linear-regression.html"><a href="heritability-from-a-linear-regression.html#assumptions-10-mins"><i class="fa fa-check"></i><b>19.3.3</b> Assumptions (10 mins)</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="heritability-from-a-linear-regression.html"><a href="heritability-from-a-linear-regression.html#takeaways-16"><i class="fa fa-check"></i><b>19.4</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-4.html"><a href="part-4.html"><i class="fa fa-check"></i>Part 4: Interactions Between Species and Community Structure</a></li>
<li class="chapter" data-level="20" data-path="lotka-volterra-competition.html"><a href="lotka-volterra-competition.html"><i class="fa fa-check"></i><b>20</b> Lotka-Volterra competition</a>
<ul>
<li class="chapter" data-level="20.1" data-path="lotka-volterra-competition.html"><a href="lotka-volterra-competition.html#worked-example-15"><i class="fa fa-check"></i><b>20.1</b> Worked example</a></li>
<li class="chapter" data-level="20.2" data-path="lotka-volterra-competition.html"><a href="lotka-volterra-competition.html#your-task-16"><i class="fa fa-check"></i><b>20.2</b> Your task</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="lotka-volterra-competition.html"><a href="lotka-volterra-competition.html#the-questions"><i class="fa fa-check"></i><b>20.2.1</b> The questions</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="lotka-volterra-competition.html"><a href="lotka-volterra-competition.html#takeaways-17"><i class="fa fa-check"></i><b>20.3</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="lotka-volterra-predator-prey-dynamics.html"><a href="lotka-volterra-predator-prey-dynamics.html"><i class="fa fa-check"></i><b>21</b> Lotka-Volterra predator-prey dynamics</a>
<ul>
<li class="chapter" data-level="21.1" data-path="lotka-volterra-predator-prey-dynamics.html"><a href="lotka-volterra-predator-prey-dynamics.html#background-16"><i class="fa fa-check"></i><b>21.1</b> Background</a></li>
<li class="chapter" data-level="21.2" data-path="lotka-volterra-predator-prey-dynamics.html"><a href="lotka-volterra-predator-prey-dynamics.html#worked-example-16"><i class="fa fa-check"></i><b>21.2</b> Worked example</a></li>
<li class="chapter" data-level="21.3" data-path="lotka-volterra-predator-prey-dynamics.html"><a href="lotka-volterra-predator-prey-dynamics.html#your-task-17"><i class="fa fa-check"></i><b>21.3</b> Your task</a></li>
<li class="chapter" data-level="21.4" data-path="lotka-volterra-predator-prey-dynamics.html"><a href="lotka-volterra-predator-prey-dynamics.html#optional-extras"><i class="fa fa-check"></i><b>21.4</b> Optional extras</a></li>
<li class="chapter" data-level="21.5" data-path="lotka-volterra-predator-prey-dynamics.html"><a href="lotka-volterra-predator-prey-dynamics.html#r-version"><i class="fa fa-check"></i><b>21.5</b> R-version</a>
<ul>
<li class="chapter" data-level="21.5.1" data-path="lotka-volterra-predator-prey-dynamics.html"><a href="lotka-volterra-predator-prey-dynamics.html#reference"><i class="fa fa-check"></i><b>21.5.1</b> Reference</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="lotka-volterra-predator-prey-dynamics.html"><a href="lotka-volterra-predator-prey-dynamics.html#takeaways-18"><i class="fa fa-check"></i><b>21.6</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><i class="fa fa-check"></i><b>22</b> Continuous-time Lotka-Volterra Predator-Prey Model in R</a>
<ul>
<li class="chapter" data-level="22.1" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#background-17"><i class="fa fa-check"></i><b>22.1</b> Background</a></li>
<li class="chapter" data-level="22.2" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#worked-example-17"><i class="fa fa-check"></i><b>22.2</b> Worked example</a></li>
<li class="chapter" data-level="22.3" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#your-task-18"><i class="fa fa-check"></i><b>22.3</b> Your task</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#step-0-create-a-new-script"><i class="fa fa-check"></i><b>22.3.1</b> Step 0: Create a new script</a></li>
<li class="chapter" data-level="22.3.2" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#step-1-load-necessary-libraries"><i class="fa fa-check"></i><b>22.3.2</b> Step 1: Load Necessary Libraries</a></li>
<li class="chapter" data-level="22.3.3" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#step-2-define-the-model"><i class="fa fa-check"></i><b>22.3.3</b> Step 2: Define the Model</a></li>
<li class="chapter" data-level="22.3.4" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#step-3-set-parameters-and-initial-conditions"><i class="fa fa-check"></i><b>22.3.4</b> Step 3: Set Parameters and Initial Conditions</a></li>
<li class="chapter" data-level="22.3.5" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#step-4-simulate-the-model"><i class="fa fa-check"></i><b>22.3.5</b> Step 4: Simulate the Model</a></li>
<li class="chapter" data-level="22.3.6" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#step-5-visualise-the-dynamics"><i class="fa fa-check"></i><b>22.3.6</b> Step 5: Visualise the Dynamics</a></li>
<li class="chapter" data-level="22.3.7" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#questions-11"><i class="fa fa-check"></i><b>22.3.7</b> Questions</a></li>
<li class="chapter" data-level="22.3.8" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#conclusion"><i class="fa fa-check"></i><b>22.3.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="continuous-time-lotka-volterra-predator-prey-model-in-r.html"><a href="continuous-time-lotka-volterra-predator-prey-model-in-r.html#takeaways-19"><i class="fa fa-check"></i><b>22.4</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><i class="fa fa-check"></i><b>23</b> Discrete-time Lotka-Volterra Predator-Prey Model in R</a>
<ul>
<li class="chapter" data-level="23.1" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#learning-outcomes-4"><i class="fa fa-check"></i><b>23.1</b> Learning outcomes</a></li>
<li class="chapter" data-level="23.2" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#worked-example-18"><i class="fa fa-check"></i><b>23.2</b> Worked example</a></li>
<li class="chapter" data-level="23.3" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#introduction-1"><i class="fa fa-check"></i><b>23.3</b> Introduction</a></li>
<li class="chapter" data-level="23.4" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#step-1-define-the-model"><i class="fa fa-check"></i><b>23.4</b> Step 1: Define the Model</a></li>
<li class="chapter" data-level="23.5" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#step-2-set-parameters-and-initial-conditions"><i class="fa fa-check"></i><b>23.5</b> Step 2: Set Parameters and Initial Conditions</a></li>
<li class="chapter" data-level="23.6" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#step-3-simulate-the-model"><i class="fa fa-check"></i><b>23.6</b> Step 3: Simulate the Model</a></li>
<li class="chapter" data-level="23.7" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#step-4-visualise-the-dynamics"><i class="fa fa-check"></i><b>23.7</b> Step 4: Visualise the Dynamics</a>
<ul>
<li class="chapter" data-level="23.7.1" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#population-dynamics-over-time-1"><i class="fa fa-check"></i><b>23.7.1</b> Population Dynamics Over Time</a></li>
<li class="chapter" data-level="23.7.2" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#phase-plot-with-zngis-1"><i class="fa fa-check"></i><b>23.7.2</b> Phase Plot with ZNGIs</a></li>
</ul></li>
<li class="chapter" data-level="23.8" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#conclusion-1"><i class="fa fa-check"></i><b>23.8</b> Conclusion</a></li>
<li class="chapter" data-level="23.9" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#your-task-19"><i class="fa fa-check"></i><b>23.9</b> Your task</a></li>
<li class="chapter" data-level="23.10" data-path="discrete-time-lotka-volterra-predator-prey-model-in-r.html"><a href="discrete-time-lotka-volterra-predator-prey-model-in-r.html#takeaways-20"><i class="fa fa-check"></i><b>23.10</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-5.html"><a href="part-5.html"><i class="fa fa-check"></i>Part 5: Animal behaviour, altruism and sexual selection</a></li>
<li class="chapter" data-level="24" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html"><i class="fa fa-check"></i><b>24</b> Game theory: Hawks and doves</a>
<ul>
<li class="chapter" data-level="24.1" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#background-18"><i class="fa fa-check"></i><b>24.1</b> Background</a></li>
<li class="chapter" data-level="24.2" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#worked-example-19"><i class="fa fa-check"></i><b>24.2</b> Worked example</a></li>
<li class="chapter" data-level="24.3" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#your-task-20"><i class="fa fa-check"></i><b>24.3</b> Your task</a></li>
<li class="chapter" data-level="24.4" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#the-payoff-table"><i class="fa fa-check"></i><b>24.4</b> The payoff table</a>
<ul>
<li class="chapter" data-level="24.4.1" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#hypotheses"><i class="fa fa-check"></i><b>24.4.1</b> Hypotheses</a></li>
<li class="chapter" data-level="24.4.2" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#game-one"><i class="fa fa-check"></i><b>24.4.2</b> GAME ONE</a></li>
<li class="chapter" data-level="24.4.3" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#game-two"><i class="fa fa-check"></i><b>24.4.3</b> GAME TWO</a></li>
</ul></li>
<li class="chapter" data-level="24.5" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#summarise-results"><i class="fa fa-check"></i><b>24.5</b> SUMMARISE RESULTS</a></li>
<li class="chapter" data-level="24.6" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#acknowledgement"><i class="fa fa-check"></i><b>24.6</b> Acknowledgement</a></li>
<li class="chapter" data-level="24.7" data-path="game-theory-hawks-and-doves.html"><a href="game-theory-hawks-and-doves.html#takeaways-21"><i class="fa fa-check"></i><b>24.7</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-6.html"><a href="part-6.html"><i class="fa fa-check"></i>Part 6: Solutions/answers</a></li>
<li class="chapter" data-level="25" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html"><i class="fa fa-check"></i><b>25</b> Solutions and “take-home” messages</a>
<ul>
<li class="chapter" data-level="25.1" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#how-to-use-this-section"><i class="fa fa-check"></i><b>25.1</b> How to use this section</a></li>
<li class="chapter" data-level="25.2" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-the-blind-watchmaker"><i class="fa fa-check"></i><b>25.2</b> Solutions: The blind watchmaker</a></li>
<li class="chapter" data-level="25.3" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-bug-hunt-camouflage"><i class="fa fa-check"></i><b>25.3</b> Solutions: Bug hunt camouflage</a></li>
<li class="chapter" data-level="25.4" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-geometric-growth"><i class="fa fa-check"></i><b>25.4</b> Solutions: Geometric growth</a></li>
<li class="chapter" data-level="25.5" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-estimating-population-growth-rate"><i class="fa fa-check"></i><b>25.5</b> Solutions: Estimating Population Growth Rate</a></li>
<li class="chapter" data-level="25.6" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-stochastic-population-growth"><i class="fa fa-check"></i><b>25.6</b> Solutions: Stochastic population growth</a></li>
<li class="chapter" data-level="25.7" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-basic-logistic-population-growth"><i class="fa fa-check"></i><b>25.7</b> Solutions: Basic logistic population growth</a></li>
<li class="chapter" data-level="25.8" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-deeper-into-logistic-growth"><i class="fa fa-check"></i><b>25.8</b> Solutions: Deeper into logistic growth</a>
<ul>
<li class="chapter" data-level="25.8.1" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#relationship-between-logistic-and-exponential-growth-equations"><i class="fa fa-check"></i><b>25.8.1</b> Relationship between Logistic and Exponential growth equations</a></li>
<li class="chapter" data-level="25.8.2" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#type-of-dynamics-depends-on-r_m."><i class="fa fa-check"></i><b>25.8.2</b> Type of dynamics depends on <span class="math inline">\(r_m\)</span>.</a></li>
<li class="chapter" data-level="25.8.3" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#you-can-obtain-parameters-from-graphs"><i class="fa fa-check"></i><b>25.8.3</b> You can obtain parameters from graphs</a></li>
<li class="chapter" data-level="25.8.4" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#time-lag"><i class="fa fa-check"></i><b>25.8.4</b> Time lag</a></li>
<li class="chapter" data-level="25.8.5" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#chaotic-dynamics"><i class="fa fa-check"></i><b>25.8.5</b> Chaotic dynamics</a></li>
</ul></li>
<li class="chapter" data-level="25.9" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-life-tables-and-survivorship-types"><i class="fa fa-check"></i><b>25.9</b> Solutions: Life tables and survivorship types</a></li>
<li class="chapter" data-level="25.10" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-matrix-population-modelling"><i class="fa fa-check"></i><b>25.10</b> Solutions: Matrix population modelling</a></li>
<li class="chapter" data-level="25.11" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-how-many-eggs-should-a-bird-lay"><i class="fa fa-check"></i><b>25.11</b> Solutions: How many eggs should a bird lay?</a></li>
<li class="chapter" data-level="25.12" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-trade-offs-and-the-force-of-selection"><i class="fa fa-check"></i><b>25.12</b> Solutions: Trade-offs and the force of selection</a></li>
<li class="chapter" data-level="25.13" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-hardy-weinberg-equilibrium"><i class="fa fa-check"></i><b>25.13</b> Solutions: Hardy-Weinberg equilibrium</a>
<ul>
<li class="chapter" data-level="25.13.1" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#problem-1"><i class="fa fa-check"></i><b>25.13.1</b> Problem 1</a></li>
<li class="chapter" data-level="25.13.2" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#problem-2"><i class="fa fa-check"></i><b>25.13.2</b> Problem 2</a></li>
<li class="chapter" data-level="25.13.3" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#problem-3"><i class="fa fa-check"></i><b>25.13.3</b> Problem 3</a></li>
<li class="chapter" data-level="25.13.4" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#problem-4"><i class="fa fa-check"></i><b>25.13.4</b> Problem 4</a></li>
</ul></li>
<li class="chapter" data-level="25.14" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-gene-pool-model"><i class="fa fa-check"></i><b>25.14</b> Solutions: Gene pool model</a>
<ul>
<li class="chapter" data-level="25.14.1" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#discussion-questions"><i class="fa fa-check"></i><b>25.14.1</b> Discussion questions</a></li>
<li class="chapter" data-level="25.14.2" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#bottlenecks-1"><i class="fa fa-check"></i><b>25.14.2</b> Bottlenecks</a></li>
<li class="chapter" data-level="25.14.3" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#broader-questions"><i class="fa fa-check"></i><b>25.14.3</b> Broader questions</a></li>
</ul></li>
<li class="chapter" data-level="25.15" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-neutral-or-adaptive-evolution-in-humans"><i class="fa fa-check"></i><b>25.15</b> Solutions: Neutral or adaptive evolution in humans</a></li>
<li class="chapter" data-level="25.16" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-heritability"><i class="fa fa-check"></i><b>25.16</b> Solutions: Heritability</a></li>
<li class="chapter" data-level="25.17" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-lotka-volterra-competition"><i class="fa fa-check"></i><b>25.17</b> Solutions: Lotka-Volterra competition</a></li>
<li class="chapter" data-level="25.18" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-lotka-volterra-predator-prey-dynamics"><i class="fa fa-check"></i><b>25.18</b> Solutions: Lotka-Volterra predator-prey dynamics</a></li>
<li class="chapter" data-level="25.19" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-the-legend-of-ambalappuzha"><i class="fa fa-check"></i><b>25.19</b> Solutions: The legend of Ambalappuzha</a></li>
<li class="chapter" data-level="25.20" data-path="solutions-and-take-home-messages.html"><a href="solutions-and-take-home-messages.html#solutions-from-population-biology-to-fitness"><i class="fa fa-check"></i><b>25.20</b> Solutions: From population biology to fitness</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="results-of-the-hawk-dove-games.html"><a href="results-of-the-hawk-dove-games.html"><i class="fa fa-check"></i><b>26</b> Results of the hawk-dove games</a>
<ul>
<li class="chapter" data-level="26.0.1" data-path="results-of-the-hawk-dove-games.html"><a href="results-of-the-hawk-dove-games.html#game-2---different-opponents"><i class="fa fa-check"></i><b>26.0.1</b> Game 2 - different opponents</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-7.html"><a href="part-7.html"><i class="fa fa-check"></i>Part 7: Appendix - extras</a></li>
<li class="chapter" data-level="27" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html"><i class="fa fa-check"></i><b>27</b> Exponential growth in detail</a>
<ul>
<li class="chapter" data-level="27.0.1" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#nomenclature"><i class="fa fa-check"></i><b>27.0.1</b> Nomenclature</a></li>
<li class="chapter" data-level="27.1" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#discrete-time-model"><i class="fa fa-check"></i><b>27.1</b> Discrete time model</a>
<ul>
<li class="chapter" data-level="27.1.1" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#calculating-n-for-any-future-time-point"><i class="fa fa-check"></i><b>27.1.1</b> Calculating N for any future time point</a></li>
<li class="chapter" data-level="27.1.2" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#applying-the-model"><i class="fa fa-check"></i><b>27.1.2</b> Applying the model</a></li>
</ul></li>
<li class="chapter" data-level="27.2" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#real-world-application-breeding-pairs-of-merlin-falco-columbarius"><i class="fa fa-check"></i><b>27.2</b> Real-World Application: Breeding Pairs of Merlin (Falco columbarius)</a>
<ul>
<li class="chapter" data-level="27.2.1" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#observations-and-context"><i class="fa fa-check"></i><b>27.2.1</b> Observations and Context</a></li>
<li class="chapter" data-level="27.2.2" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#applying-the-exponential-growth-model"><i class="fa fa-check"></i><b>27.2.2</b> Applying the Exponential Growth Model</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#continuous-time-model"><i class="fa fa-check"></i><b>27.3</b> Continuous time model</a>
<ul>
<li class="chapter" data-level="27.3.1" data-path="exponential-growth-in-detail.html"><a href="exponential-growth-in-detail.html#zero-population-growth"><i class="fa fa-check"></i><b>27.3.1</b> Zero population growth</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="28" data-path="the-legend-of-ambalappuzha.html"><a href="the-legend-of-ambalappuzha.html"><i class="fa fa-check"></i><b>28</b> The legend of Ambalappuzha</a>
<ul>
<li class="chapter" data-level="28.1" data-path="the-legend-of-ambalappuzha.html"><a href="the-legend-of-ambalappuzha.html#animalsplants-not-grains-of-rice"><i class="fa fa-check"></i><b>28.1</b> Animals/plants, not grains of rice</a>
<ul>
<li class="chapter" data-level="28.1.1" data-path="the-legend-of-ambalappuzha.html"><a href="the-legend-of-ambalappuzha.html#quick-exercise-optional"><i class="fa fa-check"></i><b>28.1.1</b> Quick exercise (optional)</a></li>
<li class="chapter" data-level="28.1.2" data-path="the-legend-of-ambalappuzha.html"><a href="the-legend-of-ambalappuzha.html#discussion-prompts"><i class="fa fa-check"></i><b>28.1.2</b> Discussion prompts</a></li>
</ul></li>
<li class="chapter" data-level="28.2" data-path="the-legend-of-ambalappuzha.html"><a href="the-legend-of-ambalappuzha.html#optional-try-these-calculations-in-r"><i class="fa fa-check"></i><b>28.2</b> Optional: Try these calculations in R</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="from-population-biology-to-fitness.html"><a href="from-population-biology-to-fitness.html"><i class="fa fa-check"></i><b>29</b> From population biology to fitness</a>
<ul>
<li class="chapter" data-level="29.1" data-path="from-population-biology-to-fitness.html"><a href="from-population-biology-to-fitness.html#an-in-silico-experiment"><i class="fa fa-check"></i><b>29.1</b> An <em>in silico</em> experiment</a></li>
<li class="chapter" data-level="29.2" data-path="from-population-biology-to-fitness.html"><a href="from-population-biology-to-fitness.html#the-link-to-fitness"><i class="fa fa-check"></i><b>29.2</b> The link to fitness</a></li>
<li class="chapter" data-level="29.3" data-path="from-population-biology-to-fitness.html"><a href="from-population-biology-to-fitness.html#introducing-a-trade-off"><i class="fa fa-check"></i><b>29.3</b> Introducing a trade-off</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="from-plain-english-to-a-matrix-model.html"><a href="from-plain-english-to-a-matrix-model.html"><i class="fa fa-check"></i><b>30</b> From plain English to a matrix model</a>
<ul>
<li class="chapter" data-level="30.1" data-path="from-plain-english-to-a-matrix-model.html"><a href="from-plain-english-to-a-matrix-model.html#background-19"><i class="fa fa-check"></i><b>30.1</b> Background</a></li>
<li class="chapter" data-level="30.2" data-path="from-plain-english-to-a-matrix-model.html"><a href="from-plain-english-to-a-matrix-model.html#worked-example-20"><i class="fa fa-check"></i><b>30.2</b> Worked example</a></li>
<li class="chapter" data-level="30.3" data-path="from-plain-english-to-a-matrix-model.html"><a href="from-plain-english-to-a-matrix-model.html#your-task-21"><i class="fa fa-check"></i><b>30.3</b> Your task</a></li>
<li class="chapter" data-level="30.4" data-path="from-plain-english-to-a-matrix-model.html"><a href="from-plain-english-to-a-matrix-model.html#takeaways-22"><i class="fa fa-check"></i><b>30.4</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="continuous-traits-from-discrete-genes.html"><a href="continuous-traits-from-discrete-genes.html"><i class="fa fa-check"></i><b>31</b> Continuous traits from discrete genes</a>
<ul>
<li class="chapter" data-level="31.1" data-path="continuous-traits-from-discrete-genes.html"><a href="continuous-traits-from-discrete-genes.html#background-20"><i class="fa fa-check"></i><b>31.1</b> Background</a></li>
<li class="chapter" data-level="31.2" data-path="continuous-traits-from-discrete-genes.html"><a href="continuous-traits-from-discrete-genes.html#worked-example-21"><i class="fa fa-check"></i><b>31.2</b> Worked example</a></li>
<li class="chapter" data-level="31.3" data-path="continuous-traits-from-discrete-genes.html"><a href="continuous-traits-from-discrete-genes.html#your-task-22"><i class="fa fa-check"></i><b>31.3</b> Your task</a></li>
<li class="chapter" data-level="31.4" data-path="continuous-traits-from-discrete-genes.html"><a href="continuous-traits-from-discrete-genes.html#takeaways-23"><i class="fa fa-check"></i><b>31.4</b> Takeaways</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="building-a-phylogenetic-tree.html"><a href="building-a-phylogenetic-tree.html"><i class="fa fa-check"></i><b>32</b> Building a phylogenetic tree</a>
<ul>
<li class="chapter" data-level="32.1" data-path="building-a-phylogenetic-tree.html"><a href="building-a-phylogenetic-tree.html#background-21"><i class="fa fa-check"></i><b>32.1</b> Background</a></li>
<li class="chapter" data-level="32.2" data-path="building-a-phylogenetic-tree.html"><a href="building-a-phylogenetic-tree.html#worked-example-22"><i class="fa fa-check"></i><b>32.2</b> Worked example</a></li>
<li class="chapter" data-level="32.3" data-path="building-a-phylogenetic-tree.html"><a href="building-a-phylogenetic-tree.html#your-task-23"><i class="fa fa-check"></i><b>32.3</b> Your task</a></li>
<li class="chapter" data-level="32.4" data-path="building-a-phylogenetic-tree.html"><a href="building-a-phylogenetic-tree.html#takeaways-24"><i class="fa fa-check"></i><b>32.4</b> Takeaways</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">BB512 - Population Biology and Evolution</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="solutions-and-take-home-messages" class="section level1 hasAnchor" number="25">
<h1><span class="header-section-number">25</span> Solutions and “take-home” messages<a href="solutions-and-take-home-messages.html#solutions-and-take-home-messages" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this section you will find the solutions and/or main take home messages of the practical exercises used in this course.</p>
<div id="how-to-use-this-section" class="section level2 hasAnchor" number="25.1">
<h2><span class="header-section-number">25.1</span> How to use this section<a href="solutions-and-take-home-messages.html#how-to-use-this-section" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Use these solutions to check your reasoning after you attempt the tasks. If your answer differs, focus on the logic rather than the final number.</p>
</div>
<div id="solutions-the-blind-watchmaker" class="section level2 hasAnchor" number="25.2">
<h2><span class="header-section-number">25.2</span> Solutions: The blind watchmaker<a href="solutions-and-take-home-messages.html#solutions-the-blind-watchmaker" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><em>What happens if selection is turned OFF?</em></li>
</ul>
<p>If there is no selection, then there is no adaptation. Selection is required to retain the changes and pass to the next generation. With no selection the result is purely random.</p>
<ul>
<li><em>Does the number of generations affect whether the target phrase is reached?</em></li>
</ul>
<p>Yes, if the phrase is complex, it may take many generations to reach. Increasing the number of generations will improve the chance that the target is reached.</p>
<ul>
<li><em>Does the speed of reaching the target phrase depend on the length of the phrase?</em></li>
</ul>
<p>Yes. Shorter target phrases are achieved quicker than longer ones.</p>
<ul>
<li><em>How does this simulation differ from real natural selection?</em></li>
</ul>
<p>Two ways. Firstly, natural selection does not have a specific long-term goal (i.e. target). It is simply that the better survivors are more represented in the next generation. Secondly, in natural selection each intermediate step needs to be advantageous compared to the previous step, which is not necessarily the case here.</p>
</div>
<div id="solutions-bug-hunt-camouflage" class="section level2 hasAnchor" number="25.3">
<h2><span class="header-section-number">25.3</span> Solutions: Bug hunt camouflage<a href="solutions-and-take-home-messages.html#solutions-bug-hunt-camouflage" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><em>What happens to the average colour of the bug population with time as you hunt?</em></li>
</ul>
<p>The colour evolves to become more similar to the background colour because you (the hunter) find it harder to find these better-camouflaged individuals.</p>
<ul>
<li><em>What happens to your hunting efficiency?</em></li>
</ul>
<p>Your hunting efficiency tends to decrease with time because the bugs are evolving to be harder to see. They are evolving camouflaged colours.</p>
<ul>
<li><em>Would you say that the bug population becomes worse or better adapted to their environment?</em></li>
</ul>
<p>The population becomes better-adapted to their environment with time.</p>
<ul>
<li><em>Can you explain how this happens?</em></li>
</ul>
<p>You (the hunter) kill the most obvious bugs first (i.e. those with contrasting colours to the background). These are the individuals that are not well-adapted to the environment. The survivors have offspring that are similar to them, while the ones you kill leave no offspring. So as time goes on, the population becomes dominated by individuals that are well-camouflaged.</p>
<ul>
<li><em>After simulating in one environment (e.g. poppy field) for a few minutes, pause then switch to another environment. Are the bugs now well- or poorly-adapted to their environment?</em></li>
</ul>
<p>Changing the environment means that the individuals are now poorly-adapted to their environment. This is because the individuals now find themselves in an environment that they did not evolve in. Their evolved camouflage does not work so well in a new environment.</p>
<ul>
<li><em>Do the genotypes of individuals change (e.g. with individual age)?</em></li>
</ul>
<p>No, individuals’ genotypes are fixed. The change in the population occurs because of selection of individuals to reproduce. Better-adapted individuals are more likely to reproduce.</p>
<ul>
<li><em>Increasing the “max-mutation-step” makes bug offspring less like their parents. How do you think this will influence the speed of adaptation of the bugs?</em></li>
</ul>
<p>Increasing the amount of variation in offspring will tend to speed up adaptation. However, there are limits: too much variation can cause maladaptation of offspring. For example, if a parent is well-adapted (perfectly camouflaged), too much variation in offspring could lead to some offspring being poorly-camouflaged and therefore vulnerable to predation.</p>
</div>
<div id="solutions-geometric-growth" class="section level2 hasAnchor" number="25.4">
<h2><span class="header-section-number">25.4</span> Solutions: Geometric growth<a href="solutions-and-take-home-messages.html#solutions-geometric-growth" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can find the completed Excel file <a href="https://www.dropbox.com/s/sfxu1lbrxyqt462/GeometricGrowth%20-%20complete.xlsx?dl=1">here</a>.</p>
<p>Take home messages:</p>
<ul>
<li>The rate of exponential/geometric growth depends on the population growth rate.</li>
<li>Lambda (<span class="math inline">\(\lambda\)</span>) values <span class="math inline">\(&lt;1\)</span> lead to a exponential <em>decrease</em>, while values <span class="math inline">\(&gt;1\)</span> lead to exponential growth. A <span class="math inline">\(\lambda\)</span> of 1 indicates no change.</li>
<li>Exponential growth is unlimited. This is unrealistic because very soon competition (what Darwin called “The struggle for existence”) will soon take effect as the population runs out of space or resources. Nevertheless, the model is useful and realistic for some limited situations (e.g. early population growth for new invaders)</li>
<li>Growth trajectories can be plotted on the <em>natural scale</em> or on a <em>log scale</em>. Exponential growth (or decline) plotted on a log scale is a straight line. This could be useful to infer biological processes (or the lack of them). For example, exponential growth in population size indicates that there are no forces currently limiting the population (e.g. predators/competition/management actions).</li>
<li>The slope of the population growth on the natural log scale can tell you what <span class="math inline">\(\lambda\)</span> is. The “opposite” of <em>ln</em> is <em>exp</em>, so you can ask Excel to `=EXP(slope).</li>
</ul>
</div>
<div id="solutions-estimating-population-growth-rate" class="section level2 hasAnchor" number="25.5">
<h2><span class="header-section-number">25.5</span> Solutions: Estimating Population Growth Rate<a href="solutions-and-take-home-messages.html#solutions-estimating-population-growth-rate" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can find the completed Excel file <a href="https://www.dropbox.com/scl/fi/sxvtkuwxs0mn9ohgwh0ot/EstimatingGrowth_completed.xlsx?rlkey=lzefpmqt3ishxze4weoy9nz65&amp;dl=1">here</a>.</p>
<ol style="list-style-type: decimal">
<li>What does the log-transformed plot of population size over time tell you about the population’s growth trend? Does the population grow exponentially?</li>
</ol>
<ul>
<li>The log-transformed plot should show a straight line if the population is growing exponentially, because the natural logarithm of an exponentially growing population will linearise the exponential curve. The slope of this line represents the natural log of the population growth rate <span class="math inline">\(log(\lambda)\)</span>. If the line has a positive slope, it indicates the population is growing; if it’s flat, the population is stable; and if it’s negative, the population is shrinking.</li>
<li>In this exercise, assuming <span class="math inline">\(\lambda &gt; 1\)</span>, the population is indeed growing exponentially, which will be reflected by a positively sloped line in the log-transformed plot.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>What is the estimated population growth rate (<span class="math inline">\(\lambda\)</span>) based on your regression analysis?</li>
</ol>
<ul>
<li>From the linear regression performed on the log-transformed data, the slope of the line corresponds to <span class="math inline">\(log(\lambda)\)</span>. To find <span class="math inline">\(\lambda\)</span>, exponentiate the slope: <span class="math inline">\(\lambda = e^{\text{slope}}\)</span>.</li>
<li>For example, if the slope of the regression line is 0.086, then <span class="math inline">\(\lambda = e^{0.086} \approx 1.09\)</span>. This means the population grows by approximately 9% per year, matching the initial assumption of <span class="math inline">\(\lambda = 1.09\)</span>.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>What assumptions does this model make? Discuss any potential real-world factors that might affect the accuracy of your estimate for <span class="math inline">\(\lambda\)</span>.</li>
</ol>
<ul>
<li><p>The model assumes a constant growth rate over time. It does not account for environmental changes, resource limitations, or carrying capacity (which would lead to logistic rather than exponential growth).</p></li>
<li><p>The model also assumes no immigration, emigration, or catastrophic events that might disrupt the population trend.</p></li>
<li><p><strong>Environmental variability</strong>: In reality, populations experience fluctuations due to weather, food availability, disease, and other stochastic factors, which can cause growth rates to change over time.</p></li>
<li><p><strong>Density dependence</strong>: As populations grow larger, they may face resource limitations or increased competition, leading to a slowdown in growth, which would not be captured by a simple geometric model.</p></li>
<li><p><strong>Measurement errors</strong>: In practice, the measurement of population sizes may not be precise, as discussed earlier with the introduction of noise. These errors can lead to inaccuracies in estimating <span class="math inline">\(\lambda\)</span>.</p></li>
</ul>
</div>
<div id="solutions-stochastic-population-growth" class="section level2 hasAnchor" number="25.6">
<h2><span class="header-section-number">25.6</span> Solutions: Stochastic population growth<a href="solutions-and-take-home-messages.html#solutions-stochastic-population-growth" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can find the completed Excel file <a href="https://www.dropbox.com/s/baao06vi0c0quns/StochasticPopulationGrowth-complete.xlsx?dl=1">here</a>.</p>
<p>Take home messages:</p>
<ul>
<li>Population growth rates are unlikely to be constant through time.</li>
<li>Environmental stochasticity will cause changes through time in vital rates (birth/death) which will influence <span class="math inline">\(\lambda\)</span> (and <span class="math inline">\(r_m\)</span>).</li>
<li>We can model environmental stochasticity using a distribution of population growth rates instead of a single deterministic value.</li>
<li>We then can randomly draw growth rate values from this distribution for each time-step in a population projection.</li>
<li>The “spread” or uncertainty in the population size at a future time point depends on (i) the spread (variance) of the distribution and (ii) the amount of time elapsed.</li>
<li>We can repeatedly simulate a population projection (e.g. in R, or more laboriously in Excel) to get a feel for the likely fate of a population. E.g. “what percent of the projections show extinction within 50 years?”.</li>
<li>We can use this relatively simple and “unrealistic” model to nevertheless get an intuition about general trends in population dynamics and extinction risk.</li>
<li>Extinction probability increases as (i) initial population size decreases; (ii) variance increases; (iii) growth rates decrease; (iv) the time frame increases.</li>
</ul>
</div>
<div id="solutions-basic-logistic-population-growth" class="section level2 hasAnchor" number="25.7">
<h2><span class="header-section-number">25.7</span> Solutions: Basic logistic population growth<a href="solutions-and-take-home-messages.html#solutions-basic-logistic-population-growth" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You were asked to use the Excel sheet to answer some questions about logistic growth by examining the graphs.</p>
<p><strong>First – take a look at Graph 1</strong>.</p>
<ul>
<li><em>What is the maximum population size?</em></li>
<li><em>How does this compare to carrying capacity (K)?</em></li>
<li><em>What do you predict to happen if you increase K to 300?</em></li>
<li><em>Try doing that. Were you correct?</em></li>
</ul>
<p>You should notice that when the population growth rate (<span class="math inline">\(r_m\)</span>) is around 1 or lower, the maximum population size is the same as the carrying capacity (<span class="math inline">\(K\)</span>). As you change <span class="math inline">\(K\)</span>, this maximum population size will change accordingly.</p>
<p>If <span class="math inline">\(r_m\)</span> is markedly greater than 1, then the population size can exceed the carrying capacity. This is because the population grows so fast that it “<em>overshoots</em>” carrying capacity and then fluctuates around K.</p>
<ul>
<li><em>At what time do you reach the maximum population size?</em></li>
<li><em>If you halved growth rate (r_m) to 0.4, what do you think will happen to this time? </em></li>
<li><em>Try doing that. Were you correct?</em></li>
</ul>
<p>You should notice that the time taken to reach the maximum population size is related to the growth rate (<span class="math inline">\(r_m\)</span>). As you increase <span class="math inline">\(r_m\)</span>, the time taken to hit the maximum population size decreases. If you halve the growth rate, the time taken to reach maximum population size is doubled.</p>
<ul>
<li><em>What do you think will happen if you increase growth rate to 1.8?</em></li>
<li><em>Try that… were you correct?</em></li>
<li><em>What do you notice about the population size through time?</em></li>
<li><em>How does the maximum population size compare with the carrying capacity?</em></li>
<li><em>How would you describe the dynamics of this population?</em></li>
</ul>
<p>You should notice that the population overshoots carrying capacity (<span class="math inline">\(K\)</span>), then oscillates around <span class="math inline">\(K\)</span> with damped oscillations that gradually move towards <span class="math inline">\(K\)</span>. Therefore if a population has even a moderate population growth rate, and if it has density-dependence, then it can fluctuate in numbers without any extrinsic factor (like weather) acting.</p>
<ul>
<li><em>What happens if you increase the growth rate even more, to 2 or 2.1?</em></li>
<li><em>And even more to 2.8, 2.9 or 3?</em></li>
<li><em>How would you describe these dynamics?</em></li>
<li><em>Is there a limit to how high <span class="math inline">\(r_m\)</span> can be? (hint: populations go extinct if N &lt; 0).</em></li>
</ul>
<p>You should notice that as you increase <span class="math inline">\(r_m\)</span> the nature of the oscillations changes. In fact, this is predictable: If <span class="math inline">\(r_m &lt; 1.0\)</span>, then population will approach <span class="math inline">\(K\)</span> smoothly.</p>
<p>If <span class="math inline">\(1.0 &lt; r_m &lt; 2.0\)</span>, then oscillations of decreasing amplitude around K.</p>
<p>If <span class="math inline">\(2.0&lt; r_m &lt; 2.57\)</span>, then stable, cyclic oscillations around K . They can be 1 or 2+ point stable limit cycles.</p>
<p>If <span class="math inline">\(r_m &gt; 2.57\)</span>, then population will fluctuate chaotically.</p>
<p>If <span class="math inline">\(r_m\)</span> is too high, the population will fluctuate and crash to extinction.</p>
<p><em>Compare the population trajectory in Graph 1 for populations with <span class="math inline">\(r_m\)</span>= 2.8 and 2.81. Then compare the trajectories where you fix <span class="math inline">\(r_m\)</span> at 2.8 but vary initial population size by a small amount (e.g. 1). Imagine you were a population manager – would these populations be easy or hard to predict? What kinds of species have high population growth rates like these?</em></p>
<p>When <span class="math inline">\(r_m\)</span> is high (<span class="math inline">\(&gt;2.57\)</span>) the population dynamics become extremely hard (impossible) to predict because they are chaotic. This means that even a very small change in <span class="math inline">\(r_m\)</span> (which could simply be measurement error) will mean that predicted population size next year is suddenly very different. This would cause big problems to a population manager.</p>
<p>Many pest species and diseases have very high population growth rates. For example, locusts, or measles. This is one reason why it is hard to predict when the next pest/disease outbreak will happen</p>
<p><strong>Now let’s turn to Graph 2</strong></p>
<p><em>In graph 2, notice that the per capita growth rate always declines linearly with population size (<span class="math inline">\(N\)</span>). Where does it cross the x-axis line? Modify the carrying capacity (<span class="math inline">\(K\)</span>) – what do you notice?</em></p>
<p>The line describing per capita growth rate crosses the x-axis (population size) at <span class="math inline">\(K\)</span>. i.e. if <span class="math inline">\(K = 100\)</span>, the line crosses at 100. If you change <span class="math inline">\(K\)</span>, the intercept on the axis also changes accordingly. The line intercepts the x-axis at this point no matter what the population growth rate is. It intercepts the y-axis at <span class="math inline">\(r_m\)</span>.</p>
<p><em>How would the same plots look for regular exponential growth?</em></p>
<p>The equivalent plot (for Graph 2) for exponential growth would be a horizontal line - because population growth rate does NOT depend on population size.</p>
</div>
<div id="solutions-deeper-into-logistic-growth" class="section level2 hasAnchor" number="25.8">
<h2><span class="header-section-number">25.8</span> Solutions: Deeper into logistic growth<a href="solutions-and-take-home-messages.html#solutions-deeper-into-logistic-growth" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="relationship-between-logistic-and-exponential-growth-equations" class="section level3 hasAnchor" number="25.8.1">
<h3><span class="header-section-number">25.8.1</span> Relationship between Logistic and Exponential growth equations<a href="solutions-and-take-home-messages.html#relationship-between-logistic-and-exponential-growth-equations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The logistic growth equation simplifies to become the exponential growth equation if you set <span class="math inline">\(K\)</span> to be infinite (<span class="math inline">\(\infty\)</span>). The simplification goes like this:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\frac{d N}{d t}=r N\left(1-\frac{N}{K}\right)\)</span></li>
<li><span class="math inline">\(\frac{d N}{d t}=r N\left(1-\frac{N}{\infty}\right)\)</span></li>
<li><span class="math inline">\(\frac{d N}{d t}=r N\left(1-0\right)\)</span></li>
<li><span class="math inline">\(\frac{d N}{d t}=r N \times 1\)</span></li>
<li><span class="math inline">\(\frac{d N}{d t}=r N\)</span></li>
</ol>
<p>This simplification also works with the discrete version of the equation, <span class="math inline">\(N_{t+1}=N_{t}+r_{d} N_{t}\left(1-\frac{N_{t}}{K}\right)\)</span>.</p>
</div>
<div id="type-of-dynamics-depends-on-r_m." class="section level3 hasAnchor" number="25.8.2">
<h3><span class="header-section-number">25.8.2</span> Type of dynamics depends on <span class="math inline">\(r_m\)</span>.<a href="solutions-and-take-home-messages.html#type-of-dynamics-depends-on-r_m." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As you increase <span class="math inline">\(r_m\)</span>, the dynamics of the population changes. At low <span class="math inline">\(r_m\)</span> population size (<span class="math inline">\(N\)</span>) simply converges on the carrying capacity, <span class="math inline">\(K\)</span>. As <span class="math inline">\(r_m\)</span> you will see damped oscillations whereby <span class="math inline">\(N\)</span> overshoots <span class="math inline">\(K\)</span> and then oscillates and converges to <span class="math inline">\(K\)</span>. Then you will see cycles where the population size oscillates <em>around</em> <span class="math inline">\(K\)</span>. The cycles can be simple two-point cycles (where <span class="math inline">\(N\)</span> bounces between two points), or more complex with <span class="math inline">\(N\)</span> bouncing between four-points (or more). In fact, the critical values of <span class="math inline">\(r_m\)</span> that define the type of dynamics are fixed: if we know <span class="math inline">\(r_m\)</span> we can predict the type of dynamics.</p>
<p>The behaviour of the population dynamics depends only on <span class="math inline">\(r_m\)</span>, not on <span class="math inline">\(K\)</span> or starting population size (<span class="math inline">\(N_0\)</span>) (as long as <span class="math inline">\(N_0 &gt; K\)</span>).</p>
</div>
<div id="you-can-obtain-parameters-from-graphs" class="section level3 hasAnchor" number="25.8.3">
<h3><span class="header-section-number">25.8.3</span> You can obtain parameters from graphs<a href="solutions-and-take-home-messages.html#you-can-obtain-parameters-from-graphs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You should notice that having some information about what the parameters are will allow you to sketch the dynamics. Conversely, if you have a graph showing aspects of the population dynamics, you could figure out what the parameters of the logistic equation are.</p>
<p>For Exponential growth, population size is unlimited and will grow exponentially if <span class="math inline">\(r\)</span> is <span class="math inline">\(&gt;0\)</span> (or <span class="math inline">\(\lambda &gt; 1\)</span>). Logistic growth will show some kind of limit (damped oscillation, or whatever), as the population size is attracted to <span class="math inline">\(K\)</span> in some way.</p>
<p>In logistic growth, the per capita growth rate declines as population size increases, and reaches <span class="math inline">\(0\)</span> when <span class="math inline">\(N = K\)</span>. In exponential growth, the per capita growth rate remains constant and unaffected by <span class="math inline">\(N\)</span>. Therefore the graphs of growth rate vs. N will be very different: Logistic = a negative slope, exponential = a horizontal line.</p>
</div>
<div id="time-lag" class="section level3 hasAnchor" number="25.8.4">
<h3><span class="header-section-number">25.8.4</span> Time lag<a href="solutions-and-take-home-messages.html#time-lag" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Time lagged density dependence results in oscillations. Therefore if we see oscillations in dynamics it could be due to a particular <span class="math inline">\(r_m\)</span> value or lagged density dependence.</p>
</div>
<div id="chaotic-dynamics" class="section level3 hasAnchor" number="25.8.5">
<h3><span class="header-section-number">25.8.5</span> Chaotic dynamics<a href="solutions-and-take-home-messages.html#chaotic-dynamics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Chaotic dynamics are deterministic in the sense that if you have the same initial conditions you will get the same results (dynamics). However, small changes in any parameters (<span class="math inline">\(N_0\)</span>, <span class="math inline">\(K\)</span>, or <span class="math inline">\(r_m\)</span>) will lead to very different dynamics - so in that sense, because of measurement error, the population dynamics would be very hard to predict in practice.</p>
</div>
</div>
<div id="solutions-life-tables-and-survivorship-types" class="section level2 hasAnchor" number="25.9">
<h2><span class="header-section-number">25.9</span> Solutions: Life tables and survivorship types<a href="solutions-and-take-home-messages.html#solutions-life-tables-and-survivorship-types" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The take home messages for this exercise are that life tables are a rich source of information on the life history of a population or species. From a simple accounting of ages at death and fertility we can obtain information about the “shape” of the survivorship trajectory: do most deaths happen early or late? Is mortality risk constant with age? We can also calculate measures including <strong>generation time</strong>, <span class="math inline">\(R_0\)</span> and population growth rate. You should know what these measures mean.</p>
<p>You should understand the relationship between mortality risk and survivorship curve. In other words, you should be able to describe, or do a rough sketch of mortality risk with age, if you have a survivorship curve (or vice versa).</p>
<p>The completed Excel spreadsheet is <a href="https://www.dropbox.com/s/j8uv2wf7nz0ygmp/Life%20tables%20exercise%20-%20complete.xlsx?dl=1">here</a>.</p>
</div>
<div id="solutions-matrix-population-modelling" class="section level2 hasAnchor" number="25.10">
<h2><span class="header-section-number">25.10</span> Solutions: Matrix population modelling<a href="solutions-and-take-home-messages.html#solutions-matrix-population-modelling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The main take home messages for this class are that you should:
(1) understand, and be able to draw or interpret life cycle diagram;
(2) be able to (roughly) parameterise a model shown in the life cycle diagram;
(3) be able to write out a matrix model (the square of numbers) for a given life cycle diagram (and <em>vice versa</em>).
(4) understand how population projection works, and to therefore interpret a figure or description showing a population projection.
(5) understand what an elasticity matrix tells us (it tells us the relative importance of the transitions for population growth)
(6) understand the concept of doing an LTRE to investigate management options.</p>
</div>
<div id="solutions-how-many-eggs-should-a-bird-lay" class="section level2 hasAnchor" number="25.11">
<h2><span class="header-section-number">25.11</span> Solutions: How many eggs should a bird lay?<a href="solutions-and-take-home-messages.html#solutions-how-many-eggs-should-a-bird-lay" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can find a completed Excel spreadsheet <a href="https://www.dropbox.com/s/tcpxmdfvm35jzgr/How%20many%20eggs%20-%20answers.xlsx?dl=1">here</a>.</p>
<p>The take-home message is that the trade-off between number of eggs and juvenile survival leads to an optimum number of eggs required to maximise reproductive success (i.e. number of surviving chicks).</p>
<p>You can move this optimum if the trade-off is changed. For example, if you increase survival of the chicks from larger clutches, then the optimum number of eggs will increase.</p>
<p>This fact reminds us that the environment (e.g. predation risk and resource abundance) will be an important factor in determining the evolution of life history parameters (like average number of babies).</p>
</div>
<div id="solutions-trade-offs-and-the-force-of-selection" class="section level2 hasAnchor" number="25.12">
<h2><span class="header-section-number">25.12</span> Solutions: Trade-offs and the force of selection<a href="solutions-and-take-home-messages.html#solutions-trade-offs-and-the-force-of-selection" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><em>Simulate this by adding 1 to fertility (mx) in year 1 (the benefit) but reducing survival to 0 (all die) at age 25 (the cost). What is the fitness of this strategy?</em></p>
<p>Fitness (R0) would be 50.76 (compared to 49.81).</p>
<p><em>By setting survival to 0 at other ages, determine how many years of life could be lost before this cost is no longer worth bearing. Is this surprising?</em></p>
<p>You could “kill” the species at 18, losing 8 years of life, before the new strategy of a small increase in fertility at the expense of years of life at the end of life becomes unfavourable. In other words, a cost of losing 8 yrs of life is worth bearing if the benefit is an extra baby in year 1.</p>
<p><em>Now reset everything (mx =10; survival = 0.8). Recall what fitness was when you added 1 to mx at age 1 (R0=50.811).
If, instead of adding to mx at age 1 you were to increase mx at age 25, how much would you need to increase it to reach this figure?</em></p>
<p>At age 25 you would need to increase Fertility from 10 to 222 to reach the same level of improvement in fitness as increasing Fertility from 10 to 11 at age 1.</p>
<p><em>What about at age 20?</em> 10 to 80
<em>Age 15?</em> 10 to 33
<em>Age 10?</em> 10 to 18
<em>Age 5?</em> 10 to 13</p>
<p><em>What do you notice?</em></p>
<p>You should notice that changes made at younger ages have a bigger effect than those at older ages. I have plotted this to the right. The plot shows the amount of increase in fertility that would be required to raise fitness (R0) from 49.81 to &gt;50.81 at ages 1 through to 25 (i.e. the figures you estimated above). You can see that you only need to change fertility a little bit at young ages, but you would need to make BIG changes at older ages.</p>
<p><em>Reset everything again (mx =10; survival = 0.8). Set mx from age 15 onwards to be 0. Now alter survival rate after this point (at ages 15-25). What happens to fitness?</em></p>
<p>You should notice that any changes you make to survival AFTER reproduction has been completed will have no effect on fitness. In other words evolution “doesn’t care about you” after you have finished with reproduction.</p>
</div>
<div id="solutions-hardy-weinberg-equilibrium" class="section level2 hasAnchor" number="25.13">
<h2><span class="header-section-number">25.13</span> Solutions: Hardy-Weinberg equilibrium<a href="solutions-and-take-home-messages.html#solutions-hardy-weinberg-equilibrium" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Answers to the Hardy-Weinberg questions.</p>
<p>Remember the basic formulas:
<span class="math inline">\(p^2 + 2pq + q^2 = 1\)</span> and <span class="math inline">\(p + q = 1\)</span></p>
<p><span class="math inline">\(p\)</span> = frequency of the dominant allele in the population</p>
<p><span class="math inline">\(q\)</span> = frequency of the recessive allele in the population</p>
<p><span class="math inline">\(p^2\)</span> = percentage of homozygous dominant individuals</p>
<p><span class="math inline">\(q^2\)</span> = percentage of homozygous recessive individuals</p>
<p><span class="math inline">\(2pq\)</span> = percentage of heterozygous individuals</p>
<div id="problem-1" class="section level3 hasAnchor" number="25.13.1">
<h3><span class="header-section-number">25.13.1</span> Problem 1<a href="solutions-and-take-home-messages.html#problem-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The frequency of the <em>aa</em> genotype: 36%, as given in the problem itself.</p>
<p>The frequency of the <em>a</em> allele: The frequency of aa is 36%, which means that <span class="math inline">\(q^2 = 0.36\)</span>, by definition. If <span class="math inline">\(q^2 = 0.36\)</span>, then <span class="math inline">\(q = 0.6\)</span>. Since <span class="math inline">\(q\)</span> equals the frequency of the “a” allele, the frequency is 60%.</p>
<p>The frequency of the <em>A</em> allele: Since <span class="math inline">\(q = 0.6\)</span>, and <span class="math inline">\(p + q = 1\)</span>, then <span class="math inline">\(p = 0.4\)</span>; the frequency of <em>A</em> is equal to <span class="math inline">\(p\)</span> (see the basic H-W equations), so the answer is 40%.</p>
<p>The frequencies of the genotypes <em>AA</em> and <em>Aa</em>: The frequency of <em>AA</em> is equal to <span class="math inline">\(p^2\)</span>, and the frequency of <em>Aa</em> is equal to <span class="math inline">\(2pq\)</span>. So, using the information above, the frequency of <em>AA</em> is 16% (i.e. <span class="math inline">\(p^2 = 0.4 x 0.4 = 0.16\)</span> and Aa is 48% (<span class="math inline">\(2pq = 2 \times 0.4 \times 0.6 = 0.48\)</span>).</p>
<p>The frequencies of the two possible phenotypes if <em>A</em> is completely dominant over <em>a</em>: Because <em>A</em> is totally dominate over <em>a</em>, the dominant phenotype will show if either the homozygous <em>AA</em> or heterozygous <em>Aa</em> genotypes occur. The recessive phenotype is controlled by the homozygous <em>aa</em> genotype. Therefore, the frequency of the dominant phenotype equals the sum of the frequencies of <em>AA</em> and <em>Aa</em>, and the recessive phenotype is simply the frequency of <em>aa</em>. Therefore, the dominant frequency is 64% and, in the first part of this question above, you have already shown that the recessive frequency is 36%.</p>
</div>
<div id="problem-2" class="section level3 hasAnchor" number="25.13.2">
<h3><span class="header-section-number">25.13.2</span> Problem 2<a href="solutions-and-take-home-messages.html#problem-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>9% = 0.09 = ss = <span class="math inline">\(q^2\)</span>. To find <span class="math inline">\(q\)</span>, simply take the square root of 0.09 to get 0.3. Since <span class="math inline">\(p = 1 - 0.3\)</span>, then <span class="math inline">\(p\)</span> must equal 0.7. <span class="math inline">\(2pq = 2 \times 0.7 \times 0.3 = 0.42\)</span>, so 42% of the population are heterozygotes (carriers).</p>
</div>
<div id="problem-3" class="section level3 hasAnchor" number="25.13.3">
<h3><span class="header-section-number">25.13.3</span> Problem 3<a href="solutions-and-take-home-messages.html#problem-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The frequency of the recessive allele. Since we believe that the homozygous recessive for this gene (<span class="math inline">\(q^2\)</span>) represents 4% (i.e. = 0.04), the square root (<span class="math inline">\(q\)</span>) is therefore 0.2 (20%).</p>
<p>The frequency of the dominant allele. Since <span class="math inline">\(q = 0.2\)</span>, and <span class="math inline">\(p + q = 1\)</span>, then <span class="math inline">\(p = 0.8\)</span> (80%).</p>
<p>The frequency of heterozygous individuals. The frequency of heterozygous individuals is equal to <span class="math inline">\(2pq\)</span>. In this case, <span class="math inline">\(2pq = 0.32\)</span>, which means that the frequency of individuals heterozygous for this gene is equal to 32% (i.e. <span class="math inline">\(2 \times 0.8 \times 0.2) = 0.32\)</span>.</p>
</div>
<div id="problem-4" class="section level3 hasAnchor" number="25.13.4">
<h3><span class="header-section-number">25.13.4</span> Problem 4<a href="solutions-and-take-home-messages.html#problem-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The first thing you’ll need to do is obtain <span class="math inline">\(p\)</span> and <span class="math inline">\(q\)</span>. So, since white is recessive (i.e. <em>bb</em>), and 40% of the butterflies are white, then <em>bb</em> = <span class="math inline">\(q^2\)</span> = 0.4.
To determine <span class="math inline">\(q\)</span>, which is the frequency of the recessive allele in the population, take the square root of <span class="math inline">\(q^2\)</span> which is 0.632. So, <span class="math inline">\(q = 0.63\)</span>. Since <span class="math inline">\(p + q = 1\)</span>, then <span class="math inline">\(p\)</span> must be <span class="math inline">\(1 - 0.63 = 0.37\)</span>.</p>
<p>Now then, to answer our questions. First, what is the percentage of butterflies in the population that are heterozygous? Well, that would be <span class="math inline">\(2pq\)</span> so the answer is <span class="math inline">\(2 \times 0.37\times 0.63 = 0.47\)</span>. Second, what is the frequency of homozygous dominant individuals? That would be <span class="math inline">\(p^2\)</span> or <span class="math inline">\(0.37^2 = 0.14\)</span>.</p>
</div>
</div>
<div id="solutions-gene-pool-model" class="section level2 hasAnchor" number="25.14">
<h2><span class="header-section-number">25.14</span> Solutions: Gene pool model<a href="solutions-and-take-home-messages.html#solutions-gene-pool-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="discussion-questions" class="section level3 hasAnchor" number="25.14.1">
<h3><span class="header-section-number">25.14.1</span> Discussion questions<a href="solutions-and-take-home-messages.html#discussion-questions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><strong>How does population size affect the variation through time in allele frequencies? Why do you see these patterns?</strong>
<ul>
<li>Population size plays a crucial role in determining the variation in allele frequencies over time. In small populations, random genetic drift has a more pronounced effect, leading to larger fluctuations in allele frequencies. This is because in smaller populations, the random sampling of alleles during reproduction can result in significant changes in allele frequencies. In contrast, in larger populations, these random fluctuations are dampened due to the “averaging” effect of having more individuals. Hence, allele frequencies in larger populations tend to be more stable over time.</li>
</ul></li>
<li><strong>How does the probability of <em>fixation</em> change with population size?</strong>
<ul>
<li>The probability of fixation of a new mutation is equal to its initial frequency. For a new mutation appearing in a population, its initial frequency is 1/2N, where N is the population size. Thus, in smaller populations, a new allele has a slightly higher chance of becoming fixed compared to in larger populations. However, it’s essential to note that while the probability of fixation is higher in smaller populations, the overall genetic drift effect is also more pronounced, which means alleles might be lost or fixed more rapidly.</li>
</ul></li>
<li><strong>When the population size is large (say 1000), is it still possible for alleles to become fixed?</strong>
<ul>
<li>Yes, it is still possible for alleles to become fixed in a large population, but it typically takes a longer time compared to smaller populations. The larger the population, the more generations it usually takes for an allele to become fixed purely by chance (genetic drift). However, other factors like selection can expedite this process.</li>
</ul></li>
<li><strong>Are rare alleles (defined with allele frequency) more or less likely to be lost than common ones? What implications does this have for new alleles (mutations)?</strong>
<ul>
<li>Rare alleles are more likely to be lost from a population than common ones due to genetic drift. This is especially true in small populations where random events can have a more pronounced impact on allele frequencies. For new alleles (which start as rare alleles when they first appear), this means they have a higher likelihood of being lost from the population before they can increase in frequency. However, if a new mutation provides a selective advantage, it can increase in frequency and become common, reducing its chance of being lost.</li>
</ul></li>
</ol>
</div>
<div id="bottlenecks-1" class="section level3 hasAnchor" number="25.14.2">
<h3><span class="header-section-number">25.14.2</span> Bottlenecks<a href="solutions-and-take-home-messages.html#bottlenecks-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Of course, let’s dive into the answers for the discussion questions related to genetic bottlenecks:</p>
<ol style="list-style-type: decimal">
<li><strong>How does a genetic bottleneck influence the genetic composition of the population?</strong>
<ul>
<li><strong>Answer:</strong> A genetic bottleneck results in a sudden and drastic reduction in the size of a population. This means that only a subset of the genetic variation present before the bottleneck remains in the population that survives. As a consequence, the genetic composition of the population post-bottleneck is often less diverse. Certain alleles may be lost entirely, while others might become more prevalent or even fixed. This change in allele frequencies due to the bottleneck can lead to reduced genetic diversity and can make the population more vulnerable to diseases, environmental changes, and other threats because of the lack of genetic variability.</li>
</ul></li>
<li><strong>How might a genetic bottleneck impact the probability of genetic fixation?</strong>
<ul>
<li><strong>Answer:</strong> A genetic bottleneck can significantly increase the probability of genetic fixation, especially if the bottleneck is severe and the population size is drastically reduced. When the population size is small, random genetic drift has a more pronounced effect, leading to rapid changes in allele frequencies. In such scenarios, certain alleles might quickly become fixed in the population purely by chance, even if they don’t confer any selective advantage. Conversely, beneficial alleles could also be lost entirely, a phenomenon known as “drift override.”</li>
</ul></li>
<li><strong>Does the severity of the bottleneck (i.e. length and population size) matter?</strong>
<ul>
<li><strong>Answer:</strong> Yes, the severity of the bottleneck, both in terms of its duration (length) and the remaining population size, plays a crucial role in determining its genetic consequences. A more extended bottleneck or one that drastically reduces the population size can lead to a more significant loss of genetic diversity. The longer a population remains small, the more time there is for genetic drift to affect allele frequencies, leading to the potential loss or fixation of alleles. Similarly, the smaller the surviving population, the greater the influence of random sampling effects on genetic composition. Thus, both the duration and the intensity of the bottleneck are critical factors in determining its genetic impact.</li>
</ul></li>
</ol>
</div>
<div id="broader-questions" class="section level3 hasAnchor" number="25.14.3">
<h3><span class="header-section-number">25.14.3</span> Broader questions<a href="solutions-and-take-home-messages.html#broader-questions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><strong>What are the limitations of this simulation? What other real-world factors and complexities are not considered in this simplified model?</strong>
<ul>
<li><strong>Answer:</strong> The simulation is a simplified representation of real-world gene pool dynamics. Some of the limitations include:
<ul>
<li><strong>Selection Pressure:</strong> The model does not account for natural selection, where certain alleles may confer a survival or reproductive advantage.</li>
<li><strong>Migration:</strong> In the real world, populations are not always isolated. Gene flow between populations due to migration can significantly influence allele frequencies.</li>
<li><strong>Mutations:</strong> Over time, new alleles can arise in a population due to mutations, introducing additional genetic variability.</li>
<li><strong>Non-Random Mating:</strong> The model assumes random mating, but in nature, there might be preferences or restrictions that influence mating choices.</li>
<li><strong>Environmental Factors:</strong> In real-world scenarios, changing environments can influence which alleles are beneficial or detrimental.</li>
</ul></li>
</ul></li>
<li><strong>Why is genetic diversity important to a population, for example in a conservation context?</strong>
<ul>
<li><strong>Answer:</strong> Genetic diversity is crucial for the adaptability and survival of a population. In a conservation context:
<ul>
<li><strong>Resilience to Diseases:</strong> A genetically diverse population is less likely to be wiped out by a single disease, as some individuals might have resistance.</li>
<li><strong>Adaptation to Changing Environments:</strong> Diverse genes mean a higher chance that some individuals in the population have traits beneficial for surviving in changing conditions.</li>
<li><strong>Reduced Inbreeding:</strong> High genetic diversity reduces the chances of inbreeding, which can lead to the expression of deleterious recessive alleles and overall reduced fitness of the population.</li>
<li><strong>Long-Term Survival:</strong> Over many generations, genetic diversity ensures that populations can evolve and adapt to long-term changes in their environment.</li>
</ul></li>
</ul></li>
<li><strong>Can you think of real-life scenarios where understanding gene pool dynamics would be valuable, such as in conservation biology or medical genetics?</strong>
<ul>
<li><strong>Answer:</strong> Absolutely!
<ul>
<li><strong>Conservation Biology:</strong> When trying to revive endangered species, understanding gene pool dynamics can help conservationists make informed decisions about breeding programs to maintain or increase genetic diversity.</li>
<li><strong>Medical Genetics:</strong> Understanding the gene pool is crucial when studying the prevalence of genetic disorders within specific populations or tracing the origin and spread of certain genetic traits.</li>
<li><strong>Agriculture:</strong> Crop breeders often need to understand gene pool dynamics to develop strains that are resistant to diseases, pests, or changing climate conditions.</li>
<li><strong>Pharmacogenomics:</strong> In medicine, understanding how different populations metabolise or react to drugs based on their genetic makeup can be invaluable.</li>
</ul></li>
</ul></li>
<li><strong>Can you think of a way to simulate the genetics of a population that is steadily shrinking through time?</strong>
<ul>
<li><strong>Answer:</strong> To simulate a steadily shrinking population, one could adjust the model to reduce the population size in each subsequent generation. This could be achieved by setting a percentage reduction or a fixed number by which the population decreases in each time step. During each iteration of the simulation, the model would then sample from an increasingly smaller gene pool, reflecting the reduction in population size. Over time, this would likely lead to more pronounced effects of genetic drift, with alleles potentially being lost or becoming fixed at a faster rate.</li>
</ul></li>
</ol>
</div>
</div>
<div id="solutions-neutral-or-adaptive-evolution-in-humans" class="section level2 hasAnchor" number="25.15">
<h2><span class="header-section-number">25.15</span> Solutions: Neutral or adaptive evolution in humans<a href="solutions-and-take-home-messages.html#solutions-neutral-or-adaptive-evolution-in-humans" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The take home message here is that whether traits are adaptive or neutral depends on the environment.</p>
<p>Consider genes that confer antibiotic resistance on bacteria. In the absence of antibiotics, these genes are not important and are not selected for. They still evolve (if they vary among individuals and are inherited), but this evolution is neutral with no selection. On the other hand, when antibiotics are introduced to the system, those same genes are strongly selected for and evolution of the genes for antibiotic resistance is now strongly adaptive. Context matters.</p>
<p>The same is the case for traits in humans. Assuming that the traits vary among individuals and are inherited, their neutrality or adaptiveness depends on their effect on fitness. If the traits have strong effects on fitness then they will be under strong selection but if they have weak or no effects on fitness they will evolve via neutral evolution.</p>
<p>Example traits that evolve via neutral evolution include fingerprint structure and iris structure. The detailed structures are not important to fitness, but are still genetically determined, and inherited.</p>
<p>Traits like muscle strength, running speed may have been important for fitness when they helped our ancestors obtain food. In those environments, they would have been under selection and therefore evolve via adaptive evolution. In more modern times, these selection pressures are weaker.</p>
</div>
<div id="solutions-heritability" class="section level2 hasAnchor" number="25.16">
<h2><span class="header-section-number">25.16</span> Solutions: Heritability<a href="solutions-and-take-home-messages.html#solutions-heritability" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can read in data like this:</p>
<p>Though you can also use the “Wizard” in RStudio.</p>
<p>Plot the data as follows.</p>
<pre><code>## 
## Call:
## lm(formula = Offspring_value ~ Parent_value, data = pop_1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -16.9417  -3.8648  -0.2452   4.5332   9.3121 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   11.2533    10.9533   1.027    0.312    
## Parent_value   0.5678     0.1114   5.097 1.63e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.506 on 31 degrees of freedom
## Multiple R-squared:  0.4559, Adjusted R-squared:  0.4384 
## F-statistic: 25.98 on 1 and 31 DF,  p-value: 1.628e-05</code></pre>
<p><img src="BB512_files/figure-html/plotheritability-1.png" alt="" width="672" /></p>
<p>The heritability is the slope of the relationship, so is 0.568 in this case. This is fairly high heritability.</p>
<p><em>What does the heritability tell us about the amount of variation explained by genetic factors?</em></p>
<p>A heritability of 0.568 for wing length indicates that 56.8% of the observed variation in this trait within the population can be attributed to genetic factors. In other words, a significant portion of the variation in wing length is genetically determined.</p>
<p><em>What other factors might explain the remaining variation?</em></p>
<p>There are many other factors at play. The remaining 30% of variation could be due to environmental factors such as diet, climate, or social interactions. It might also include measurement error or other stochastic events.</p>
<p><em>How would the heritability estimate change if you used a different trait (e.g., beak length instead of wing length)?</em></p>
<p>Heritability is trait-specific. The heritability estimate for beak length could be higher, lower, or the same as that for wing length, depending on the genetic and environmental variances contributing to this particular trait.</p>
<p><em>What does the heritability tell us about how fast a trait might change due to selection?</em></p>
<p>A higher heritability (like 0.568) suggests that the trait would respond more quickly to selection because a large proportion of the variation is genetic. Traits with lower heritability would be slower to respond to selection as they have a larger environmental component.</p>
<p>The graph for the second population looks like this:</p>
<p>Plot the data as follows.</p>
<p><img src="BB512_files/figure-html/plotparentoffspring-1.png" alt="" width="672" /></p>
<pre><code>## 
## Call:
## lm(formula = Offspring_value ~ Parent_value, data = pop_2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.0829 -0.5187 -0.1199  0.6578  1.7023 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.22970    1.53505   0.150    0.882    
## Parent_value  0.09877    0.01590   6.212 4.07e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8022 on 35 degrees of freedom
## Multiple R-squared:  0.5244, Adjusted R-squared:  0.5108 
## F-statistic: 38.59 on 1 and 35 DF,  p-value: 4.066e-07</code></pre>
<p>For this population, the heritability (slope of the relationship) is 0.099 in this case. This is fairly low heritability.</p>
<p><em>What does the heritability tell us this time?</em></p>
<p>A heritability of 0.099 in the second population indicates that only 9.9% of the variation in wing length is attributable to genetic factors. This is substantially lower compared to the first population, suggesting that environmental factors have a greater influence on the trait in this particular population.</p>
<p><em>Can you identify any environmental factors that might explain the difference?</em></p>
<p>Various environmental factors could explain the lower heritability in the second population. These might include (but are not limited to):
Nutrition: Inadequate nutrition can lead to stunted growth or development, which could introduce a significant environmental variable into wing length. Poor nutrition might limit the expression of genes related to wing growth, thereby reducing the observed heritability as the environment (nutrition) plays a more substantial role.</p>
<p>Predation Pressure: In a population under higher predation pressure, there could be strong selection for specific wing lengths that allow for more agile flight. However, if this selection pressure varies frequently (e.g., due to fluctuations in predator populations), it could introduce more environmental variance in wing length. The heritability would then appear lower because of this inconsistency in selection pressure.
Climate: Variable climates, especially those that are more extreme, could influence the development of wing length. Cold climates may lead to smaller wings due to the need for a more rounded body shape to conserve heat (Bergmann’s rule). In contrast, hot and arid climates may lead to longer wings for more efficient soaring. If the second population is exposed to a more variable or extreme climate, this could contribute to lower heritability.
Social Structure: Different mating systems could impact heritability. For instance, if the second population has a polygamous system where a few males sire most of the offspring, genetic variance could be skewed and less representative, thus affecting heritability calculations.
e.</p>
<p><em>Can you think of any real-world applications where understanding heritability would be important?</em></p>
<ul>
<li>Agriculture: Plant and animal breeding programs often rely on heritability estimates to improve desirable traits like yield, disease resistance, or growth rate.</li>
<li>Medicine: In personalized medicine, understanding the heritability of certain conditions or responses to treatments can lead to more effective, tailored interventions.</li>
<li>Conservation Biology: For endangered species, understanding the heritability of traits related to survival and reproduction can guide conservation efforts.</li>
<li>Public Health: Understanding the heritability of traits like BMI or cholesterol levels can inform public health policies and preventative measures.</li>
<li>Psychology and Education: Knowing the heritability of cognitive traits or educational attainment can help in developing targeted educational programs.</li>
</ul>
<p><em>Violation of assumptions</em></p>
<ul>
<li>Additive Genetic Effects: Epistasis or gene-gene interactions could violate this assumption, affecting the predicted heritability.</li>
<li>No Shared Environment: If parent and offspring share significant environmental influences, like diet or habitat, this assumption is compromised.</li>
<li>Linearity: Non-linear relationships between parent and offspring traits would violate this assumption.</li>
<li>Measurement Accuracy: Instrumental errors or observer bias could invalidate this assumption.</li>
<li>Random Mating: If there is assortative mating based on the trait of interest, this assumption is violated.</li>
<li>No Selection Bias: If the sample is not representative of the population, perhaps due to selective pressures, this assumption is compromised.</li>
<li>Statistical Independence: If data from sibling or repeated measures are included, this assumption is broken.</li>
<li>No Genetic Drift or Migration: A sudden influx of new individuals or loss of existing ones due to various factors can violate this assumption.</li>
</ul>
</div>
<div id="solutions-lotka-volterra-competition" class="section level2 hasAnchor" number="25.17">
<h2><span class="header-section-number">25.17</span> Solutions: Lotka-Volterra competition<a href="solutions-and-take-home-messages.html#solutions-lotka-volterra-competition" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can find a completed Excel spreadsheet <a href="https://www.dropbox.com/s/q1qoqxhnm82uugw/9.%20LV%20Competition.xlsx?dl=1">here</a>.</p>
<p>The answers to the questions are <a href="https://www.dropbox.com/s/oz2c10bmyf8t7s6/9.%20Answers%20to%20questions.pdf?dl=1">here</a>.</p>
<p>To add to this document, you can see the conditions for coexistence in the Neal textbook (p. 278). Note that in this textbook, <span class="math inline">\(\alpha_{12}\)</span> is written as <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\alpha_{21}\)</span> is written as <span class="math inline">\(\beta\)</span></p>
<p>Let’s break down the implications of the conditions <span class="math inline">\(\alpha_{12} &lt; \frac{K_1}{K_2}\)</span> and <span class="math inline">\(\alpha_{21} &lt; \frac{K_2}{K_1}\)</span> for stable coexistence in a more intuitive way:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Carrying Capacities <span class="math inline">\(K_1\)</span> and <span class="math inline">\(K_2\)</span></strong>: Think of the carrying capacity as the maximum number of guests each species can have at their own “party” (their environment) before it becomes too crowded.</p></li>
<li><p><strong>Competition Coefficients (<span class="math inline">\(\alpha_{12}\)</span> and <span class="math inline">\(\alpha_{21}\)</span>)</strong>: The competition coefficients are like how much each uninvited guest from the other species “eats” if they crash the party. If they eat too much (high <span class="math inline">\(\alpha\)</span>), they could ruin the party by leaving not enough food for the intended guests.</p></li>
<li><p><strong>Condition <span class="math inline">\(\alpha_{12} &lt; \frac{K_1}{K_2}\)</span></strong>: This means that the uninvited guests from species 2 don’t eat too much at species 1’s party. Even if they eat some food, there’s still enough for all of species 1’s intended guests — so species 1 can still have a successful party.</p></li>
<li><p><strong>Condition <span class="math inline">\(\alpha_{21} &lt; \frac{K_2}{K_1}\)</span></strong>: Similarly, this means that the uninvited guests from species 1 are polite enough not to eat too much at species 2’s party, leaving enough for species 2’s intended guests.</p></li>
</ol>
<p>When both conditions are met, it’s like both species can have their parties without ruining each other’s. They both manage to have enough resources (food) to sustain a good number of guests (population) without the other species taking so much that it causes a problem.</p>
<p>In ecological terms, these conditions mean that while there is some competition for resources between the two species, it’s not so severe that one species would prevent the other from surviving. They can both maintain healthy populations without outcompeting each other to the point of extinction. Each species manages to “live and let live,” with neither being too greedy for the shared environment to handle.</p>
</div>
<div id="solutions-lotka-volterra-predator-prey-dynamics" class="section level2 hasAnchor" number="25.18">
<h2><span class="header-section-number">25.18</span> Solutions: Lotka-Volterra predator-prey dynamics<a href="solutions-and-take-home-messages.html#solutions-lotka-volterra-predator-prey-dynamics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can find a completed Excel spreadsheet <a href="https://www.dropbox.com/s/wet7brtgxywdqi5/10.%20Pred-PreyDynamics.xlsx?dl=1">here</a>.</p>
<p>The answers to the questions are <a href="https://www.dropbox.com/s/mt43nvqu7cjif69/10.%20Answers%20to%20Pred-Prey%20exercise.pdf?dl=1">here</a>.</p>
</div>
<div id="solutions-the-legend-of-ambalappuzha" class="section level2 hasAnchor" number="25.19">
<h2><span class="header-section-number">25.19</span> Solutions: The legend of Ambalappuzha<a href="solutions-and-take-home-messages.html#solutions-the-legend-of-ambalappuzha" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can find the completed Excel file <a href="https://www.dropbox.com/s/ybe5qhmfltuhoyv/RiceOnAChessboard_completed.xlsx?dl=1">here</a>.</p>
<p>Take home messages:</p>
<ul>
<li>Exponential/geometric growth is extremely powerful and can very quickly lead to very large numbers.</li>
</ul>
</div>
<div id="solutions-from-population-biology-to-fitness" class="section level2 hasAnchor" number="25.20">
<h2><span class="header-section-number">25.20</span> Solutions: From population biology to fitness<a href="solutions-and-take-home-messages.html#solutions-from-population-biology-to-fitness" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The matrix model with a trade off (increased juvenile survival, but reduced old adult survival) looks like this.</p>
<pre><code>A3 &lt;- matrix(c(0.00, 5.00, 1.00, 
               0.11, 0.80, 0.00, 
               0.00, 0.10, 0.20), 
            byrow = TRUE, nrow = 3)

eigs(A3)$lambda</code></pre>
<p>We can compare the <span class="math inline">\(\lambda\)</span> value from this model to the original one to ask ourselves whether the large cost is worth paying for the small benefit. It turns out that it is. You can then ask how MUCH cost would be worth bearing, by repeating the exercise and slowly reducing old-adult survival until you reach the original <span class="math inline">\(\lambda\)</span> value.</p>
<p>You should find that the cost can be huge, and still worth bearing. In fact, you could reduce old adult survival to 0 and it is still worth doing! You can even reduce old-age adult reproduction without much effect on fitness.</p>
<p>HOWEVER, changes to prime age adults are much more important. You can only reduce survival to about 0.76 (from 0.8) before the cost is not worth bearing (population growth rate falls below that of the first baseline model).</p>
<p>Thus, old-age costs are “worth it” while prime age costs are much more important. This finding is central to the evolution of senescence and life span, which we will cover later in the course.</p>
<p>Cobweb diagrams and bifurcation plots offer another way of visualising dynamics of populations (see the article about Chaos, by Mathiopoulos).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="part-6.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="results-of-the-hawk-dove-games.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/jonesor/BB512_Book/edit/master/6_01_Solutions.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["BB512.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  },
  "split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
